<script setup lang="ts">
import{computed,onMounted,reactive,ref,watch}from'vue';import{ElMessage,ElMessageBox,type UploadFile}from'element-plus';import http from'../../api/http';import TablePager from'./TablePager.vue';import{p3Catalog,type P3Field}from'../p3Catalog';
const p=defineProps<{system:string;kind:string;title:string}>(),cfg=computed(()=>p3Catalog[`${p.system}:${p.kind}`]),rows=ref<any[]>([]),page=ref(1),size=ref(20),total=ref(0),keyword=ref(''),status=ref(''),loading=ref(false),dialog=ref(false),drawer=ref(false),detailData=ref<any>({}),form=reactive<Record<string,any>>({});
function reset(){Object.keys(form).forEach(k=>delete form[k]);cfg.value.fields.forEach(f=>form[f.key]=f.type==='number'?0:'')}
async function load(){loading.value=true;try{const r=await http.get(`/${p.system}/${p.kind}`,{params:{page:page.value,size:size.value,keyword:keyword.value||undefined,status:status.value||undefined}});rows.value=r.data.data.content||[];total.value=r.data.data.totalElements||0;if(!rows.value.length&&page.value>1){page.value--;return load()}}catch(e:any){ElMessage.error(e.message||'数据加载失败')}finally{loading.value=false}}
async function create(){for(const f of cfg.value.fields)if(f.required&&!form[f.key])return ElMessage.warning(`请填写${f.label}`);try{await http.post(`/${p.system}/${p.kind}`,form);dialog.value=false;ElMessage.success('新增成功');page.value=1;load()}catch(e:any){ElMessage.error(e.message||'业务数据不正确')}}
async function detail(r:any){try{const x=await http.get(`/${p.system}/${p.kind}/${r.id}`);detailData.value=x.data.data;drawer.value=true}catch(e:any){ElMessage.error(e.message||'详情加载失败')}}
async function change(r:any,value:string){try{await http.post(`/${p.system}/${p.kind}/${r.id}/status`,{status:value});ElMessage.success('状态已更新');load()}catch(e:any){ElMessage.error(e.message||'当前状态不允许此操作')}}
async function special(r:any){try{if(p.system==='srm'&&p.kind==='rfqs'){const q=await ElMessageBox.prompt('请输入中标报价记录ID','询价定标');await http.post(`/srm/rfqs/${r.id}/award`,null,{params:{quoteId:q.value}})}else if(p.system==='srm'&&p.kind==='asns'){const q=await ElMessageBox.prompt('请输入收货仓库编码','ASN到货',{inputValue:'WH01'});await http.post(`/srm/asns/${r.id}/arrive`,null,{params:{warehouseCode:q.value}})}else if(p.system==='qms'&&p.kind==='inspections'){const q=await ElMessageBox.prompt('按“合格数,不合格数,结论”填写，例如 98,2,FAILED','检验判定');const[a,b,c]=q.value.split(',');await http.post(`/qms/inspections/${r.id}/judge`,null,{params:{qualifiedQty:a,defectQty:b,result:c}})}ElMessage.success('业务动作执行成功');load()}catch(e:any){if(e!=='cancel')ElMessage.error(e.message||'业务动作失败')}}
async function quote(r:any){try{const q=await ElMessageBox.prompt('按“供应商编码,单价,交付日期”填写，例如 SUP001,12.50,2026-12-20','登记供应商报价');const[a,b,c]=q.value.split(',');await http.post('/srm/quotes',{rfqId:r.id,supplierCode:a,unitPrice:Number(b),deliveryDate:c,status:'SUBMITTED'});ElMessage.success('供应商报价已登记')}catch(e:any){if(e!=='cancel')ElMessage.error(e.message||'报价登记失败')}}
function specialName(){if(p.system==='srm'&&p.kind==='rfqs')return'定标';if(p.system==='srm'&&p.kind==='asns')return'确认到货';if(p.system==='qms'&&p.kind==='inspections')return'检验判定';return''}
function exportCsv(){const cols=cfg.value.columns,esc=(v:any)=>`"${String(v??'').replaceAll('"','""')}"`,csv='\ufeff'+[cols.map(c=>esc(c)).join(','),...rows.value.map(r=>cols.map(c=>esc(r[c])).join(','))].join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`${p.title}.csv`;a.click();URL.revokeObjectURL(a.href)}
async function importCsv(file:UploadFile){try{const text=await file.raw!.text(),lines=text.replace(/^\ufeff/,'').split(/\r?\n/).filter(Boolean),heads=lines.shift()!.split(',').map(x=>x.replaceAll('"','').trim());for(const line of lines){const values=line.split(',').map(x=>x.replace(/^"|"$/g,'').trim()),body:any={};heads.forEach((h,i)=>body[h]=values[i]);await http.post(`/${p.system}/${p.kind}`,body)}ElMessage.success(`已导入${lines.length}条`);page.value=1;load()}catch(e:any){ElMessage.error(e.message||'导入失败，请使用导出文件的字段表头')}}
function openCreate(){reset();dialog.value=true}function fieldComponent(f:P3Field){return f.type==='select'?'el-select':f.type==='date'?'el-date-picker':'el-input'}
watch(()=>p.kind,()=>{page.value=1;load()});onMounted(load)
</script>
<template><section><div class="head"><div><span>{{system.toUpperCase()}} 业务中心</span><h1>{{title}}</h1><p>真实业务台账、状态流转、来源单号和跨系统追溯。</p></div><div class="actions"><el-upload v-if="!cfg.readonly" :show-file-list="false" :auto-upload="false" accept=".csv" @change="importCsv"><el-button>导入CSV</el-button></el-upload><el-button @click="exportCsv">导出当前页</el-button><el-button v-if="!cfg.readonly&&cfg.fields.length" type="primary" @click="openCreate">新增</el-button></div></div><el-card shadow="never"><div class="bar"><el-input v-model="keyword" placeholder="输入编号、物料或供应商" clearable @keyup.enter="page=1;load()"/><el-input v-model="status" placeholder="输入状态编码" clearable @keyup.enter="page=1;load()"/><el-button type="primary" @click="page=1;load()">查询</el-button><el-button @click="keyword='';status='';page=1;load()">重置</el-button></div><el-table :data="rows" v-loading="loading" stripe empty-text="暂无业务数据"><el-table-column v-for="k in cfg.columns" :key="k" :prop="k" :label="$zhKey(k)" min-width="125" show-overflow-tooltip><template #default="{row}">{{$zh(row[k])}}</template></el-table-column><el-table-column label="操作" width="270" fixed="right"><template #default="{row}"><el-button link @click="detail(row)">详情</el-button><el-button v-if="system==='srm'&&kind==='rfqs'" link @click="quote(row)">供应商报价</el-button><el-button v-if="specialName()" link type="success" @click="special(row)">{{specialName()}}</el-button><el-dropdown v-if="cfg.statuses?.length" @command="(v:string)=>change(row,v)"><el-button link type="primary">状态操作</el-button><template #dropdown><el-dropdown-menu><el-dropdown-item v-for="s in cfg.statuses" :key="s.value" :command="s.value">{{s.label}}</el-dropdown-item></el-dropdown-menu></template></el-dropdown></template></el-table-column></el-table><TablePager v-model:page="page" v-model:size="size" :total="total" @change="load"/></el-card>
<el-dialog v-model="dialog" :title="`新增${title}`" width="720"><el-form label-width="120px" class="form"><el-form-item v-for="f in cfg.fields" :key="f.key" :label="f.label" :required="f.required"><component :is="fieldComponent(f)" v-model="form[f.key]" :type="f.type==='textarea'?'textarea':f.type==='number'?'number':undefined" :rows="3" :placeholder="`请输入${f.label}`" style="width:100%" value-format="YYYY-MM-DD"><el-option v-for="o in f.options||[]" :key="o.value" :label="o.label" :value="o.value"/></component></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="create">保存</el-button></template></el-dialog>
<el-drawer v-model="drawer" :title="`${title}详情`" size="46%"><el-descriptions :column="1" border><el-descriptions-item v-for="(v,k) in detailData" :key="k" :label="$zhKey(String(k))">{{$zh(v)}}</el-descriptions-item></el-descriptions><el-divider>审计时间轴</el-divider><el-timeline><el-timeline-item :timestamp="String(detailData.updated_at||detailData.created_at||'')">当前状态：{{$zh(detailData.status||detailData.order_status||detailData.inspect_result||'已记录')}}</el-timeline-item><el-timeline-item>业务记录ID：{{detailData.id}}</el-timeline-item></el-timeline></el-drawer></section></template>
<style scoped>.head{display:flex;justify-content:space-between;align-items:end;margin-bottom:16px}.head span{color:#3976d5;font-size:11px}.head h1{margin:5px 0;color:#263f5c}.head p{color:#8391a4}.actions,.bar{display:flex;gap:8px}.bar{margin-bottom:14px}.bar .el-input{width:250px}.form{display:grid;grid-template-columns:1fr 1fr;gap:0 12px}.form :deep(.el-form-item:has(textarea)){grid-column:1/-1}</style>
