package com.mfg.crm.controller;import com.mfg.common.api.ApiResponse;import com.mfg.crm.dto.CustomerEntryCommand;import com.mfg.crm.service.CustomerEntryService;import com.mfg.crm.service.CrmP2Service;import com.mfg.mdm.entity.Customer;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.Page;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/crm") @RequiredArgsConstructor public class CrmP2Controller{private final CrmP2Service s;private final com.mfg.crm.service.CrmRecordService records;
 private final CustomerEntryService customerEntries;
 private ApiResponse<Page<Map<String,Object>>>page(String t,String k,String st,int p,int z){return ApiResponse.ok(s.list(t,k,st,p,z));}
 @GetMapping("/customers")@PreAuthorize("hasAuthority('CRM:CUSTOMER:VIEW')")public ApiResponse<Page<Customer>>customers(@RequestParam(required=false)String keyword,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size){return ApiResponse.ok(customerEntries.page(keyword,page,size));}
 @PostMapping("/customers")@PreAuthorize("hasAuthority('CRM:CUSTOMER:CREATE')")public ApiResponse<Map<String,Object>>createCustomer(@RequestBody CustomerEntryCommand command){return ApiResponse.ok(customerEntries.create(command));}
 @GetMapping("/leads")@PreAuthorize("hasAuthority('CRM:LEAD:VIEW')")public ApiResponse<Page<Map<String,Object>>>leads(@RequestParam(required=false)String keyword,@RequestParam(required=false)String status,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size){return page("crm_lead",keyword,status,page,size);}@PostMapping("/leads")@PreAuthorize("hasAuthority('CRM:LEAD:CREATE')")public ApiResponse<Map<String,Object>>lead(@RequestBody Map<String,Object>x){return ApiResponse.ok(s.createLead(x));}@PostMapping("/leads/{id}/assign")@PreAuthorize("hasAuthority('CRM:LEAD:ASSIGN')")public ApiResponse<Void>assign(@PathVariable long id,@RequestBody Map<String,Object>x){s.assign(id,x);return ApiResponse.ok();}@PostMapping("/leads/{id}/follow")@PreAuthorize("hasAuthority('CRM:LEAD:FOLLOW')")public ApiResponse<Void>follow(@PathVariable long id,@RequestBody Map<String,Object>x){s.follow(id,x);return ApiResponse.ok();}@PostMapping("/leads/{id}/convert")@PreAuthorize("hasAuthority('CRM:LEAD:CONVERT')")public ApiResponse<Map<String,Object>>convert(@PathVariable long id,@RequestBody Map<String,Object>x){return ApiResponse.ok(s.convert(id,x));}
 @GetMapping("/quotations")@PreAuthorize("hasAuthority('CRM:QUOTATION:VIEW')")public ApiResponse<Page<Map<String,Object>>>quotes(@RequestParam(required=false)String keyword,@RequestParam(required=false)String status,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size){return page("crm_quotation",keyword,status,page,size);}@PostMapping("/quotations")@PreAuthorize("hasAuthority('CRM:QUOTATION:CREATE')")public ApiResponse<Map<String,Object>>quote(@RequestBody Map<String,Object>x){return ApiResponse.ok(s.createQuote(x));}@PostMapping("/quotations/{id}/new-version")@PreAuthorize("hasAuthority('CRM:QUOTATION:NEW_VERSION')")public ApiResponse<Map<String,Object>>version(@PathVariable long id){return ApiResponse.ok(s.newVersion(id));}@PostMapping("/quotations/{id}/submit")@PreAuthorize("hasAuthority('CRM:QUOTATION:SUBMIT')")public ApiResponse<?>submitQuote(@PathVariable long id){return ApiResponse.ok(s.submit(id,"QUOTATION"));}@PostMapping("/quotations/{id}/activate")@PreAuthorize("hasAuthority('CRM:QUOTATION:ACTIVATE')")public ApiResponse<Void>activateQuote(@PathVariable long id){s.activateQuote(id);return ApiResponse.ok();}
 @GetMapping("/contracts")@PreAuthorize("hasAuthority('CRM:CONTRACT:VIEW')")public ApiResponse<Page<Map<String,Object>>>contracts(@RequestParam(required=false)String keyword,@RequestParam(required=false)String status,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size){return page("crm_contract",keyword,status,page,size);}@PostMapping("/contracts")@PreAuthorize("hasAuthority('CRM:CONTRACT:CREATE')")public ApiResponse<Map<String,Object>>contract(@RequestBody Map<String,Object>x){return ApiResponse.ok(s.createContract(x));}@PostMapping("/contracts/{id}/submit")@PreAuthorize("hasAuthority('CRM:CONTRACT:SUBMIT')")public ApiResponse<?>submitContract(@PathVariable long id){return ApiResponse.ok(s.submit(id,"CONTRACT"));}@PostMapping("/contracts/{id}/activate")@PreAuthorize("hasAuthority('CRM:CONTRACT:ACTIVATE')")public ApiResponse<Void>activate(@PathVariable long id){s.activate(id);return ApiResponse.ok();}@PostMapping("/contracts/{id}/create-order")@PreAuthorize("hasAuthority('CRM:CONTRACT:CONVERT')")public ApiResponse<Map<String,Object>>order(@PathVariable long id){return ApiResponse.ok(s.createOrder(id));}@PostMapping("/contracts/{id}/new-version")@PreAuthorize("hasAuthority('CRM:CONTRACT:CHANGE')")public ApiResponse<Map<String,Object>>contractVersion(@PathVariable long id,@RequestBody Map<String,Object>x){return ApiResponse.ok(s.newContractVersion(id,x));}
 @GetMapping("/complaints")@PreAuthorize("hasAuthority('CRM:COMPLAINT:VIEW')")public ApiResponse<Page<Map<String,Object>>>complaints(@RequestParam(required=false)String keyword,@RequestParam(required=false)String status,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size){return page("crm_complaint",keyword,status,page,size);}@PostMapping("/complaints")@PreAuthorize("hasAuthority('CRM:COMPLAINT:CREATE')")public ApiResponse<Map<String,Object>>complaint(@RequestBody Map<String,Object>x){return ApiResponse.ok(s.createComplaint(x));}@GetMapping("/forecast")@PreAuthorize("hasAuthority('CRM:FORECAST:VIEW')")public ApiResponse<Page<Map<String,Object>>>forecast(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size){return ApiResponse.ok(s.forecast(page,size));}@GetMapping("/customer-360/{code}")@PreAuthorize("hasAuthority('CRM:CUSTOMER:VIEW')")public ApiResponse<Map<String,Object>>customer(@PathVariable String code){return ApiResponse.ok(s.customer360(code));}

 @GetMapping("/leads/{id}") @PreAuthorize("hasAuthority('CRM:LEAD:VIEW')") public ApiResponse<Map<String,Object>> leadDetail(@PathVariable long id){return ApiResponse.ok(records.get("leads",id));}
 @PutMapping("/leads/{id}") @PreAuthorize("hasAuthority('CRM:LEAD:UPDATE')") public ApiResponse<Map<String,Object>> updateLead(@PathVariable long id,@RequestBody Map<String,Object>x){return ApiResponse.ok(records.update("leads",id,x));}
 @DeleteMapping("/leads/{id}") @PreAuthorize("hasAuthority('CRM:LEAD:DELETE')") public ApiResponse<Void> deleteLead(@PathVariable long id){records.delete("leads",id);return ApiResponse.ok();}
 @GetMapping("/quotations/{id}") @PreAuthorize("hasAuthority('CRM:QUOTATION:VIEW')") public ApiResponse<Map<String,Object>> quoteDetail(@PathVariable long id){return ApiResponse.ok(records.get("quotations",id));}
 @PutMapping("/quotations/{id}") @PreAuthorize("hasAuthority('CRM:QUOTATION:UPDATE')") public ApiResponse<Map<String,Object>> updateQuote(@PathVariable long id,@RequestBody Map<String,Object>x){return ApiResponse.ok(records.update("quotations",id,x));}
 @DeleteMapping("/quotations/{id}") @PreAuthorize("hasAuthority('CRM:QUOTATION:DELETE')") public ApiResponse<Void> deleteQuote(@PathVariable long id){records.delete("quotations",id);return ApiResponse.ok();}
 @GetMapping("/contracts/{id}") @PreAuthorize("hasAuthority('CRM:CONTRACT:VIEW')") public ApiResponse<Map<String,Object>> contractDetail(@PathVariable long id){return ApiResponse.ok(records.get("contracts",id));}
 @PutMapping("/contracts/{id}") @PreAuthorize("hasAuthority('CRM:CONTRACT:UPDATE')") public ApiResponse<Map<String,Object>> updateContract(@PathVariable long id,@RequestBody Map<String,Object>x){return ApiResponse.ok(records.update("contracts",id,x));}
 @DeleteMapping("/contracts/{id}") @PreAuthorize("hasAuthority('CRM:CONTRACT:DELETE')") public ApiResponse<Void> deleteContract(@PathVariable long id){records.delete("contracts",id);return ApiResponse.ok();}
 @GetMapping("/complaints/{id}") @PreAuthorize("hasAuthority('CRM:COMPLAINT:VIEW')") public ApiResponse<Map<String,Object>> complaintDetail(@PathVariable long id){return ApiResponse.ok(records.get("complaints",id));}
 @PutMapping("/complaints/{id}") @PreAuthorize("hasAuthority('CRM:COMPLAINT:UPDATE')") public ApiResponse<Map<String,Object>> updateComplaint(@PathVariable long id,@RequestBody Map<String,Object>x){return ApiResponse.ok(records.update("complaints",id,x));}
 @DeleteMapping("/complaints/{id}") @PreAuthorize("hasAuthority('CRM:COMPLAINT:DELETE')") public ApiResponse<Void> deleteComplaint(@PathVariable long id){records.delete("complaints",id);return ApiResponse.ok();}
}
