package com.mfg.crm.controller;
import com.mfg.common.api.*;import com.mfg.common.exception.BizException;import com.mfg.crm.entity.Opportunity;import com.mfg.crm.repo.OpportunityRepository;import com.mfg.mdm.entity.Customer;import com.mfg.mdm.repo.CustomerRepository;import com.mfg.mdm.service.MasterDataService;import com.mfg.security.config.CurrentUser;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.*;import org.springframework.web.bind.annotation.*;
/** 客户、商机、跟进是 CRM 的本职；订单只在赢单后交给 ERP。 */
@RestController @RequestMapping("/api/crm/opportunities") @RequiredArgsConstructor public class OpportunityController{
 private final OpportunityRepository repo;private final CustomerRepository customers;private final MasterDataService master;
 @GetMapping public ApiResponse<Page<Opportunity>> page(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size){return ApiResponse.ok(repo.findAll(PageRequest.of(Math.max(0,page-1),Math.min(200,size))));}
 @PostMapping public ApiResponse<Opportunity> create(@RequestBody Opportunity o){if(repo.existsByOpportunityNo(o.getOpportunityNo()))throw BizException.of(ErrorCode.MASTER_DATA_ALREADY_EXISTS,"商机编号已存在");Customer c=customers.findByCustomerCode(o.getCustomerCode()).orElseThrow(()->BizException.of(ErrorCode.MASTER_DATA_NOT_FOUND,"客户不存在"));master.assertConsumable(c,"CRM 商机");o.setCustomerName(c.getCustomerName());o.setOwnerUser(CurrentUser.usernameOrSystem());o.setOwnerName(CurrentUser.get().getRealName());o.setDeptCode(CurrentUser.get().getDeptCode());return ApiResponse.ok(repo.save(o));}
 @PostMapping("/{id}/stage") public ApiResponse<Opportunity> stage(@PathVariable Long id,@RequestParam String code){Opportunity o=repo.findById(id).orElseThrow(()->BizException.notFound("商机",id));if(!java.util.Set.of("LEAD","QUALIFY","PROPOSAL","NEGOTIATE","WON","LOST").contains(code))throw BizException.of(ErrorCode.MASTER_DATA_INVALID_STATE,"非法商机阶段");o.setStageCode(code);return ApiResponse.ok(repo.save(o));}
}
