package com.mfg.crm.controller;
import com.mfg.common.api.*;import com.mfg.common.exception.BizException;import com.mfg.crm.entity.*;import com.mfg.crm.repo.*;import com.mfg.mdm.entity.Customer;import com.mfg.mdm.repo.CustomerRepository;import com.mfg.mdm.service.MasterDataService;import com.mfg.security.config.CurrentUser;import lombok.RequiredArgsConstructor;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.data.domain.*;import org.springframework.web.bind.annotation.*;
/** 客户、商机、跟进是 CRM 的本职；订单只在赢单后交给 ERP。 */
@RestController @RequestMapping("/api/crm/opportunities") @RequiredArgsConstructor public class OpportunityController{
 private final OpportunityRepository repo;private final OpportunityFollowRepository follows;private final CustomerRepository customers;private final MasterDataService master;private final JdbcTemplate db;
 @GetMapping public ApiResponse<Page<Opportunity>> page(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size){return ApiResponse.ok(repo.findAll(PageRequest.of(Math.max(0,page-1),Math.min(200,size))));}
 @PostMapping public ApiResponse<Opportunity> create(@RequestBody Opportunity o){if(repo.existsByOpportunityNo(o.getOpportunityNo()))throw BizException.of(ErrorCode.MASTER_DATA_ALREADY_EXISTS,"商机编号已存在");Customer c=customers.findByCustomerCode(o.getCustomerCode()).orElseThrow(()->BizException.of(ErrorCode.MASTER_DATA_NOT_FOUND,"客户不存在"));master.assertConsumable(c,"CRM 商机");o.setCustomerName(c.getCustomerName());o.setOwnerUser(CurrentUser.usernameOrSystem());o.setOwnerName(CurrentUser.get().getRealName());o.setDeptCode(CurrentUser.get().getDeptCode());return ApiResponse.ok(repo.save(o));}
 @PostMapping("/{id}/stage") public ApiResponse<Opportunity> stage(@PathVariable Long id,@RequestBody java.util.Map<String,Object> body){String code=String.valueOf(body.getOrDefault("code",body.getOrDefault("reason",""))).trim().toUpperCase();Opportunity o=repo.findById(id).orElseThrow(()->BizException.notFound("商机",id));if(!java.util.Set.of("LEAD","QUALIFY","PROPOSAL","NEGOTIATE","WON","LOST").contains(code))throw BizException.of(ErrorCode.MASTER_DATA_INVALID_STATE,"非法商机阶段");if("WON".equals(code)){Integer count=db.queryForObject("SELECT COUNT(*) FROM src_crm.crm_quotation WHERE opportunity_no=? AND status='EFFECTIVE'",Integer.class,o.getOpportunityNo());if(count==null||count==0)throw BizException.of(ErrorCode.MASTER_DATA_INVALID_STATE,"赢单前必须存在生效报价");}if("LOST".equals(code)){String reason=String.valueOf(body.getOrDefault("reason","")).trim();if(reason.isBlank())throw BizException.of(ErrorCode.PARAM_INVALID,"丢单原因必填");db.update("UPDATE src_crm.crm_opportunity SET lost_reason=? WHERE id=?",reason,id);}o.setStageCode(code);return ApiResponse.ok(repo.save(o));}
 @GetMapping("/{id}/follows")public ApiResponse<java.util.List<OpportunityFollow>> follows(@PathVariable Long id){Opportunity o=repo.findById(id).orElseThrow(()->BizException.notFound("商机",id));return ApiResponse.ok(follows.findByOpportunityNoOrderByFollowAtDesc(o.getOpportunityNo()));}
 @PostMapping("/{id}/follows")public ApiResponse<OpportunityFollow> follow(@PathVariable Long id,@RequestBody OpportunityFollow f){Opportunity o=repo.findById(id).orElseThrow(()->BizException.notFound("商机",id));if(!java.util.Set.of("CALL","VISIT","EMAIL","MEETING").contains(f.getFollowType()))throw BizException.of(ErrorCode.MASTER_DATA_INVALID_STATE,"非法跟进类型");f.setOpportunityNo(o.getOpportunityNo());f.setFollowUser(CurrentUser.usernameOrSystem());f.setFollowAt(java.time.LocalDateTime.now());return ApiResponse.ok(follows.save(f));}
}
