package com.mfg.wms.controller;
import com.mfg.common.api.*;import com.mfg.common.exception.BizException;import com.mfg.wms.dto.StockTransactionCommand;import com.mfg.wms.entity.*;import com.mfg.wms.repo.*;import com.mfg.wms.service.InventoryService;import jakarta.validation.Valid;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.*;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/wms") @RequiredArgsConstructor public class WarehouseController{private final WarehouseLocationRepository locations;private final InventoryRepository inventories;private final StockTransactionRepository txns;private final InventoryService service;
 @GetMapping("/locations")public ApiResponse<Page<WarehouseLocation>> locations(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size){return ApiResponse.ok(locations.findAll(PageRequest.of(Math.max(0,page-1),Math.min(200,size))));}
 @PostMapping("/locations")public ApiResponse<WarehouseLocation> createLocation(@RequestBody WarehouseLocation l){if(locations.existsByLocationCode(l.getLocationCode()))throw BizException.of(ErrorCode.MASTER_DATA_ALREADY_EXISTS,"库位编码已存在");l.setAvailable(true);return ApiResponse.ok(locations.save(l));}
 @PatchMapping("/locations/{id}/availability")public ApiResponse<WarehouseLocation> availability(@PathVariable Long id,@RequestParam boolean enabled){WarehouseLocation l=locations.findById(id).orElseThrow(()->BizException.notFound("库位",id));l.setAvailable(enabled);return ApiResponse.ok(locations.save(l));}
 @GetMapping("/inventories")public ApiResponse<Page<Inventory>> inventories(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size){return ApiResponse.ok(inventories.findAll(PageRequest.of(Math.max(0,page-1),Math.min(200,size))));}
 @GetMapping("/transactions")public ApiResponse<Page<StockTransaction>> transactions(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size){return ApiResponse.ok(txns.findAll(PageRequest.of(Math.max(0,page-1),Math.min(200,size))));}
 @PostMapping("/transactions")public ApiResponse<StockTransaction> transaction(@Valid @RequestBody StockTransactionCommand c){return ApiResponse.ok(service.transact(c));}}
