package com.mfg.wms.controller;
import com.mfg.common.api.ApiResponse;import com.mfg.common.service.P3CrudService;import com.mfg.wms.dto.InventoryActionCommand;import com.mfg.wms.service.InventoryTransactionService;import jakarta.validation.Valid;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.Page;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/wms") @RequiredArgsConstructor public class WmsP3Controller{
 private final P3CrudService crud;private final InventoryTransactionService inventory;private static final Set<String>K=Set.of("receipts","putaway","inventories","inventory-actions","transfers","counts");private String kind(String k){if(!K.contains(k))throw new IllegalArgumentException("不支持的WMS对象");return k;}
 @GetMapping("/{kind}")@PreAuthorize("hasAuthority('WMS:RECORD:VIEW')")public ApiResponse<Page<Map<String,Object>>>page(@PathVariable String kind,@RequestParam(required=false)String keyword,@RequestParam(required=false)String status,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size){return ApiResponse.ok(crud.page(kind(kind),keyword,status,page,size));}
 @GetMapping("/{kind}/{id}")@PreAuthorize("hasAuthority('WMS:RECORD:VIEW')")public ApiResponse<Map<String,Object>>detail(@PathVariable String kind,@PathVariable long id){return ApiResponse.ok(crud.detail(kind(kind),id));}
 @PostMapping("/{kind}")@PreAuthorize("hasAuthority('WMS:RECORD:CREATE')")public ApiResponse<Map<String,Object>>create(@PathVariable String kind,@RequestBody Map<String,Object>x){String k=kind(kind);if(Set.of("inventories","inventory-actions","receipts").contains(k))throw new IllegalArgumentException("该对象只能由业务事务生成");return ApiResponse.ok(crud.create(k,x));}
 @PutMapping("/{kind}/{id}")@PreAuthorize("hasAuthority('WMS:RECORD:UPDATE')")public ApiResponse<Map<String,Object>>update(@PathVariable String kind,@PathVariable long id,@RequestBody Map<String,Object>x){return ApiResponse.ok(crud.update(kind(kind),id,x));}
 @DeleteMapping("/{kind}/{id}")@PreAuthorize("hasAuthority('WMS:RECORD:DELETE')")public ApiResponse<Void>delete(@PathVariable String kind,@PathVariable long id){crud.delete(kind(kind),id);return ApiResponse.ok();}
 @PostMapping("/{kind}/{id}/status")@PreAuthorize("hasAuthority('WMS:RECORD:UPDATE')")public ApiResponse<Map<String,Object>>status(@PathVariable String kind,@PathVariable long id,@RequestBody Map<String,Object>x){return ApiResponse.ok(crud.status(kind(kind),id,String.valueOf(x.get("status"))));}
 @PostMapping("/inventory-actions/{action}")@PreAuthorize("hasAuthority('WMS:INVENTORY:ACTION') or hasRole('ADMIN')")public ApiResponse<Map<String,Object>>action(@PathVariable String action,@Valid @RequestBody InventoryActionCommand c){String type=switch(action){case"freeze"->"FREEZE";case"unfreeze"->"UNFREEZE";case"quarantine"->"QUARANTINE";case"release"->"RELEASE";case"scrap"->"SCRAP";case"supplier-return"->"SUPPLIER_RETURN";default->throw new IllegalArgumentException("不支持的库存动作");};return ApiResponse.ok(inventory.action(type,c));}
 @PostMapping("/transfers/{id}/confirm")@PreAuthorize("hasAuthority('WMS:TRANSFER:CONFIRM')")public ApiResponse<Map<String,Object>>confirmTransfer(@PathVariable long id){return ApiResponse.ok(inventory.transition("wms_transfer",id,"CONFIRMED",Map.of("DRAFT",Set.of("CONFIRMED","CANCELLED"))));}
 @PostMapping("/transfers/{id}/execute")@PreAuthorize("hasAuthority('WMS:TRANSFER:EXECUTE') or hasRole('ADMIN')")public ApiResponse<Map<String,Object>>executeTransfer(@PathVariable long id,@RequestParam String idempotencyKey){return ApiResponse.ok(inventory.executeTransfer(id,idempotencyKey));}
 @PostMapping("/putaway/{id}/complete")@PreAuthorize("hasAuthority('WMS:RECORD:UPDATE')")public ApiResponse<Map<String,Object>>completePutaway(@PathVariable long id){return ApiResponse.ok(inventory.completePutaway(id));}
 @PostMapping("/counts/{id}/release")@PreAuthorize("hasAuthority('WMS:STOCK:CHECK')")public ApiResponse<Map<String,Object>>releaseCount(@PathVariable long id){return ApiResponse.ok(inventory.transition("wms_count_plan",id,"RELEASED",Map.of("DRAFT",Set.of("RELEASED","CANCELLED"))));}
 @PostMapping("/counts/{id}/review")@PreAuthorize("hasAuthority('WMS:COUNT:REVIEW')")public ApiResponse<Map<String,Object>>reviewCount(@PathVariable long id){return ApiResponse.ok(inventory.transition("wms_count_plan",id,"REVIEWING",Map.of("RELEASED",Set.of("COUNTING"),"COUNTING",Set.of("REVIEWING"))));}
 @PostMapping("/counts/{id}/post")@PreAuthorize("hasAuthority('WMS:COUNT:POST') or hasRole('ADMIN')")public ApiResponse<Map<String,Object>>postCount(@PathVariable long id,@RequestParam String idempotencyKey){return ApiResponse.ok(inventory.postCount(id,idempotencyKey));}
 @GetMapping("/counts/{id}/lines")@PreAuthorize("hasAuthority('WMS:RECORD:VIEW')")public ApiResponse<List<Map<String,Object>>>countLines(@PathVariable long id){return ApiResponse.ok(inventory.countLines(id));}
 @PostMapping("/counts/{id}/lines")@PreAuthorize("hasAuthority('WMS:RECORD:CREATE')")public ApiResponse<Map<String,Object>>addCountLine(@PathVariable long id,@RequestBody Map<String,Object>x){return ApiResponse.ok(inventory.addCountLine(id,x));}
 @PutMapping("/counts/{id}/lines/{lineId}")@PreAuthorize("hasAuthority('WMS:COUNT:REVIEW')")public ApiResponse<Map<String,Object>>updateCountLine(@PathVariable long id,@PathVariable long lineId,@RequestBody Map<String,Object>x){Object n=x.get("actualQty");return ApiResponse.ok(inventory.updateCountLine(id,lineId,n==null?null:new java.math.BigDecimal(String.valueOf(n))));}
 @DeleteMapping("/counts/{id}/lines/{lineId}")@PreAuthorize("hasAuthority('WMS:RECORD:DELETE')")public ApiResponse<Void>deleteCountLine(@PathVariable long id,@PathVariable long lineId){inventory.deleteCountLine(id,lineId);return ApiResponse.ok();}
 @PostMapping("/counts/{id}/lines/{lineId}/approve")@PreAuthorize("hasAuthority('WMS:COUNT:REVIEW')")public ApiResponse<Map<String,Object>>approveCountLine(@PathVariable long id,@PathVariable long lineId){return ApiResponse.ok(inventory.approveCountLine(id,lineId));}
}
