<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import http from '../api/http'
import TablePager from '../shared/components/TablePager.vue'
const rows=ref<any[]>([]),loading=ref(false),page=ref(1),size=ref(20),total=ref(0),status=ref('')
const detail=ref<any>(null),drawer=ref(false),substitutes=ref<Record<number,any[]>>({})
const form=reactive({lineId:0,materialCode:'',priorityNo:1,conversionRate:1})
async function load(){loading.value=true;try{const{data}=await http.get('/mdm/boms',{params:{page:page.value,size:size.value,status:status.value||undefined}});rows.value=data.data.content;total.value=data.data.totalElements;if(!rows.value.length&&total.value&&page.value>1){page.value--;await load()}}finally{loading.value=false}}
async function open(row:any){const{data}=await http.get(`/mdm/boms/${row.id}`);detail.value=data.data;drawer.value=true;substitutes.value={};for(const line of detail.value.lines||[])await loadSubstitutes(line.id)}
async function loadSubstitutes(lineId:number){const{data}=await http.get(`/mdm/boms/${detail.value.id}/lines/${lineId}/substitutes`);substitutes.value[lineId]=data.data}
async function addSubstitute(){try{await http.post(`/mdm/boms/${detail.value.id}/lines/${form.lineId}/substitutes`,form);ElMessage.success('替代料已增加');form.materialCode='';await loadSubstitutes(form.lineId)}catch(e:any){ElMessage.error(e.message||'新增失败')}}
async function disable(lineId:number,id:number){await http.delete(`/mdm/boms/${detail.value.id}/lines/${lineId}/substitutes/${id}`);ElMessage.success('替代料已停用');await loadSubstitutes(lineId)}
async function submit(r:any){try{await http.post(`/mdm/boms/${r.id}/submit`);ElMessage.success('已提交审批');await load()}catch(e:any){ElMessage.error(e.message||'提交失败')}}
function filter(){page.value=1;load()} onMounted(load)
</script>
<template><section><div class="toolbar"><div><h1 class="page-title">BOM 与替代料</h1><p class="page-subtitle">权威 BOM 版本、用料明细及发布前替代料配置</p></div><div><el-select v-model="status" clearable placeholder="全部状态" style="width:140px;margin-right:8px" @change="filter"><el-option v-for="s in ['DRAFT','PENDING','PUBLISHED','REJECTED']" :key="s" :label="$zh(s)" :value="s"/></el-select><el-button @click="load">刷新</el-button></div></div><el-card><el-table :data="rows" v-loading="loading" stripe><el-table-column prop="bomCode" label="BOM 编码"/><el-table-column prop="bomName" label="BOM 名称" min-width="180"/><el-table-column prop="productCode" label="产品"/><el-table-column prop="bomType" label="类型"/><el-table-column prop="bomVersion" label="版本"/><el-table-column prop="current" label="当前"><template #default="{row}"><el-tag v-if="row.current" type="success">当前</el-tag></template></el-table-column><el-table-column prop="status" label="状态"><template #default="{row}"><el-tag :type="row.status==='PUBLISHED'?'success':row.status==='PENDING'?'warning':'info'">{{$zh(row.status)}}</el-tag></template></el-table-column><el-table-column label="操作" width="160"><template #default="{row}"><el-button link @click="open(row)">详情</el-button><el-button v-if="row.status==='DRAFT'||row.status==='REJECTED'" link type="primary" @click="submit(row)">提交审批</el-button></template></el-table-column></el-table><TablePager v-model:page="page" v-model:size="size" :total="total" :disabled="loading" @change="load"/></el-card>
<el-drawer v-model="drawer" title="BOM明细与替代料" size="760px"><template v-if="detail"><el-descriptions :column="3" border><el-descriptions-item label="编码">{{detail.bomCode}}</el-descriptions-item><el-descriptions-item label="版本">{{detail.bomVersion}}</el-descriptions-item><el-descriptions-item label="状态">{{detail.status}}</el-descriptions-item></el-descriptions><div v-for="line in detail.lines||[]" :key="line.id" class="line"><b>{{line.lineNo}} · {{line.childMaterialCode}} {{line.childMaterialName}}</b><span>{{line.qtyPer}} {{line.unitCode}}</span><el-tag v-for="s in substitutes[line.id]||[]" :key="s.id" :type="s.status==='ACTIVE'?'success':'info'" closable @close="disable(line.id,s.id)">{{s.substituteMaterialCode}} / 优先级{{s.priorityNo}} / {{s.status}}</el-tag><el-button v-if="detail.status==='DRAFT'||detail.status==='REJECTED'" link @click="form.lineId=line.id">为此行配置替代料</el-button></div><el-form v-if="form.lineId" inline class="sub-form"><el-form-item label="替代物料"><el-input v-model="form.materialCode"/></el-form-item><el-form-item label="优先级"><el-input-number v-model="form.priorityNo" :min="1"/></el-form-item><el-form-item label="换算率"><el-input-number v-model="form.conversionRate" :min="0.000001"/></el-form-item><el-button type="primary" @click="addSubstitute">保存</el-button></el-form></template></el-drawer></section></template>
<style scoped>.toolbar{display:flex;justify-content:space-between;align-items:end;margin-bottom:16px}.line{display:flex;align-items:center;gap:10px;flex-wrap:wrap;padding:14px 0;border-bottom:1px solid #edf1f6}.line span{color:#73859a}.sub-form{margin-top:20px;padding:16px;background:#f6f9fd;border-radius:8px}</style>
