<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import http from '../api/http'

const rows = ref<any[]>([])
const loading = ref(false)
const dialog = ref(false)
const saving = ref(false)
const today = new Date().toISOString().slice(0, 10)
const form = reactive<any>({})
const reset = () => Object.assign(form, { ecnNo: '', ecnTitle: '', productCode: '', bomCode: '', changeType: 'DESIGN', changeContent: '', changeReason: '', effectiveDate: today })
const load = async () => { loading.value = true; try { const { data } = await http.get('/plm/ecns', { params: { page: 1, size: 50 } }); rows.value = data.data?.content || [] } finally { loading.value = false } }
const create = async () => { if (!form.ecnNo || !form.ecnTitle || !form.productCode || !form.changeContent) return ElMessage.warning('请填写 ECN 编号、主题、产品编码和变更内容'); saving.value = true; try { await http.post('/plm/ecns', form); ElMessage.success('工程变更单已创建'); dialog.value = false; await load() } catch (e: any) { ElMessage.error(e?.response?.data?.message || '创建失败') } finally { saving.value = false } }
const submit = async (row: any) => { try { await http.post(`/plm/ecns/${row.id}/submit`); ElMessage.success('已提交工程评审'); await load() } catch (e: any) { ElMessage.error(e?.response?.data?.message || '提交失败') } }
const implement = async (row: any) => { try { await http.post(`/plm/ecns/${row.id}/implement`); ElMessage.success('已标记实施，请在 BOM 中心创建新版本并提交审批'); await load() } catch (e: any) { ElMessage.error(e?.response?.data?.message || '实施失败') } }
onMounted(load)
</script>

<template>
  <section class="ecn-page">
    <div class="hero"><div><div class="eyebrow">PLM · 工程变更管理 CONTROL</div><h1>工程变更中心</h1><p>工程变更并不直接篡改已发布 BOM。它先走研发与工艺评审，批准后实施，再由 BOM 新版本承接制造影响。</p></div><div><el-button plain @click="load">刷新</el-button><el-button type="primary" @click="reset();dialog=true">新建 ECN</el-button></div></div>
    <div class="steps"><div><b>01</b><span>创建 ECN</span><small>描述影响产品、BOM 与变更原因</small></div><i>→</i><div><b>02</b><span>工程评审</span><small>研发、工艺、质量按流程审批</small></div><i>→</i><div><b>03</b><span>实施变更</span><small>批准后才允许实施</small></div><i>→</i><div><b>04</b><span>发布 BOM 新版</span><small>ERP / MES 消费最新受控版本</small></div></div>
    <el-card class="card" shadow="never"><template #header><div class="card-head"><span>工程变更单</span><small>工程、工艺、质量协同记录</small></div></template><el-table :data="rows" v-loading="loading" stripe><el-table-column prop="ecnNo" label="ECN 编号" min-width="145"/><el-table-column prop="ecnTitle" label="变更主题" min-width="180" show-overflow-tooltip/><el-table-column prop="productCode" label="产品编码" min-width="130"/><el-table-column prop="bomCode" label="涉及 BOM" min-width="130"/><el-table-column prop="changeType" label="变更类型" min-width="110"/><el-table-column prop="effectiveDate" label="生效日期" min-width="120"/><el-table-column prop="status" label="状态" min-width="110"><template #default="{row}"><el-tag :type="row.status==='IMPLEMENTED'?'success':row.status==='APPROVED'?'warning':'info'">{{$zh(row.status)}}</el-tag></template></el-table-column><el-table-column label="业务动作" fixed="right" width="160"><template #default="{row}"><el-button v-if="row.status==='DRAFT'" link type="primary" @click="submit(row)">提交评审</el-button><el-button v-if="row.status==='APPROVED'" link type="success" @click="implement(row)">确认实施</el-button><span v-if="!['DRAFT','APPROVED'].includes(row.status)" class="muted">等待流程</span></template></el-table-column></el-table><el-empty v-if="!loading&&!rows.length" description="暂无工程变更单，可先创建一张 ECN 演示研发变更流程。"/></el-card>
    <el-dialog v-model="dialog" title="新建工程变更单" width="680px" destroy-on-close><div class="hint">ECN 仅描述与审查工程变更；实施后仍需由 BOM 版本中心发布受控版本。</div><el-form label-position="top"><el-row :gutter="16"><el-col :span="12"><el-form-item label="ECN 编号" required><el-input v-model="form.ecnNo" placeholder="例如 ECN-202609-001"/></el-form-item></el-col><el-col :span="12"><el-form-item label="变更主题" required><el-input v-model="form.ecnTitle"/></el-form-item></el-col><el-col :span="12"><el-form-item label="产品物料编码" required><el-input v-model="form.productCode"/></el-form-item></el-col><el-col :span="12"><el-form-item label="涉及 BOM"><el-input v-model="form.bomCode"/></el-form-item></el-col><el-col :span="12"><el-form-item label="变更类型"><el-select v-model="form.changeType" style="width:100%"><el-option label="设计变更" value="DESIGN"/><el-option label="工艺变更" value="PROCESS"/><el-option label="物料替代" value="MATERIAL"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="计划生效日"><el-date-picker v-model="form.effectiveDate" value-format="YYYY-MM-DD" type="date" style="width:100%"/></el-form-item></el-col><el-col :span="24"><el-form-item label="变更内容" required><el-input v-model="form.changeContent" type="textarea" :rows="3"/></el-form-item></el-col><el-col :span="24"><el-form-item label="变更原因"><el-input v-model="form.changeReason" type="textarea" :rows="2"/></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="create">保存 ECN</el-button></template></el-dialog>
  </section>
</template>

<style scoped>
.ecn-page{max-width:1480px;margin:0 auto}.hero{display:flex;justify-content:space-between;gap:18px;padding:4px 2px 20px}.eyebrow{font-size:11px;letter-spacing:1.3px;font-weight:800;color:#3770ef}.hero h1{margin:7px 0;color:#1b3150;font-size:25px}.hero p{max-width:710px;margin:0;color:#708096;font-size:13px;line-height:1.7}.hero>div:last-child{padding-top:18px;white-space:nowrap}.steps{display:flex;align-items:center;gap:11px;margin-bottom:16px;padding:15px 19px;border:1px solid #e3eaf3;border-radius:11px;background:linear-gradient(90deg,#fbfdff,#f5f9ff)}.steps>div{min-width:0;flex:1}.steps b{display:inline-grid;place-items:center;width:22px;height:22px;margin-right:7px;border-radius:50%;background:#e2edff;color:#2d6eea;font-size:11px}.steps span{font-size:13px;font-weight:700;color:#35506f}.steps small{display:block;margin:5px 0 0 30px;color:#8898aa;font-size:11px}.steps i{color:#8ba9d4}.card{border:1px solid #e5ebf3;border-radius:12px}.card-head{display:flex;justify-content:space-between;color:#304563;font-size:14px;font-weight:700}.card-head small,.muted{color:#9ba9b9;font-weight:400;font-size:11px}.hint{margin-bottom:13px;padding:9px 11px;border-radius:7px;background:#f3f7ff;color:#6c7d91;font-size:12px}@media(max-width:850px){.hero{display:block}.steps{overflow:auto}.steps>div{min-width:145px}.steps i{min-width:16px}}
</style>
