<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.mfg</groupId>
        <artifactId>mfg-source-apps</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>app-eam</artifactId>
    <name>设备资产管理系统</name>
    <description>设备台账、状态时段、故障、维修、点检</description>

    <dependencies>
        <dependency>
            <groupId>com.mfg</groupId>
            <artifactId>shared-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mfg</groupId>
            <artifactId>shared-security</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mfg</groupId>
            <artifactId>shared-workflow</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mfg</groupId>
            <artifactId>shared-masterdata</artifactId>
        </dependency>
    </dependencies>
</project>
