<script setup lang="ts">
import { onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'
const auth=useAuthStore();const router=useRouter();onMounted(()=>!auth.user&&auth.loadMe())
const logout=async()=>{await auth.logout();router.replace('/login')}
</script>
<template><el-container class="portal-shell"><el-aside width="248px"><div class="portal-brand"><div class="brand-symbol">M</div><div><b>智造协同门户</b><small>MANUFACTURING HUB</small></div></div><div class="nav-group">统一工作台</div><el-menu router :default-active="$route.path"><el-menu-item index="/portal">系统门户</el-menu-item><el-menu-item index="/portal/approval">统一审批</el-menu-item><el-menu-item index="/portal/events">数据流转</el-menu-item><el-menu-item index="/portal/operations">运行监控</el-menu-item></el-menu><template v-if="auth.isAdmin"><div class="nav-group">平台管理</div><el-menu router :default-active="$route.path"><el-menu-item index="/portal/users">用户管理</el-menu-item><el-menu-item index="/portal/roles">角色权限</el-menu-item><el-menu-item index="/portal/organization">组织岗位</el-menu-item><el-menu-item index="/portal/audit">审计日志</el-menu-item></el-menu></template><div class="aside-status"><i></i><span>平台服务运行中</span></div></el-aside><el-container><el-header><div><b>制造业十系统协同平台</b><span>统一身份 · 统一审批 · 独立系统</span></div><div class="user"><div class="user-copy"><b>{{auth.user?.realName||'加载中'}}</b><small>{{auth.user?.positionName||auth.user?.username}}</small></div><el-avatar :size="34">{{auth.user?.realName?.slice(0,1)||'用'}}</el-avatar><el-button link type="primary" @click="logout">退出</el-button></div></el-header><el-main><router-view/></el-main></el-container></el-container></template>
<style scoped>.portal-shell{min-height:100vh}.el-aside{position:relative;padding:18px 12px 64px;background:linear-gradient(180deg,#0f2b50,#091b34);color:#dce8f6}.portal-brand{display:flex;align-items:center;gap:11px;padding:3px 10px 25px}.brand-symbol{display:grid;place-items:center;width:36px;height:36px;border-radius:11px;background:linear-gradient(135deg,#4da7ff,#4169e1);color:#fff;font-weight:900}.portal-brand b{display:block;color:#fff}.portal-brand small{display:block;margin-top:4px;color:#7897bb;font-size:9px;letter-spacing:.7px}.nav-group{margin:13px 11px 7px;color:#6f94bf;font-size:11px;letter-spacing:1px}.el-menu{border:0;background:transparent}.el-menu :deep(.el-menu-item){height:40px;margin:2px 0;border-radius:8px;color:#bfd1e6}.el-menu :deep(.el-menu-item:hover),.el-menu :deep(.el-menu-item.is-active){background:rgba(74,151,240,.18);color:#fff}.aside-status{position:absolute;bottom:20px;left:22px;display:flex;align-items:center;gap:7px;color:#89a4c4;font-size:11px}.aside-status i{width:7px;height:7px;border-radius:50%;background:#32c48d}.el-header{height:64px;display:flex;align-items:center;justify-content:space-between;padding:0 28px;border-bottom:1px solid #e9eef5;background:#fff;color:#253d5b}.el-header>div:first-child span{margin-left:13px;color:#91a0b4;font-size:12px}.user{display:flex;align-items:center;gap:10px}.user-copy{text-align:right}.user-copy b,.user-copy small{display:block}.user-copy b{font-size:13px}.user-copy small{margin-top:2px;color:#97a4b4;font-size:10px}.el-main{padding:25px 28px;background:#f3f6fa}</style>
