<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'
import { systemByCode } from '../shared/systemCatalog'
const route=useRoute();const router=useRouter();const auth=useAuthStore();const code=computed(()=>String(route.meta.system||''));const system=computed(()=>systemByCode(code.value)!)
onMounted(async()=>{if(!auth.user)await auth.loadMe();if(!auth.canAccess(code.value))router.replace('/portal')})
const logout=async()=>{await auth.logout();router.replace('/login')}
</script>
<template><el-container v-if="system" class="system-shell" :style="{'--accent':system.accent}"><el-aside width="248px"><div class="system-brand"><div class="system-symbol">{{system.shortName.slice(0,1)}}</div><div><b>{{system.shortName}}</b><small>{{system.name}}</small></div></div><div class="nav-label">业务工作区</div><el-menu router :default-active="$route.path"><el-menu-item v-for="item in system.menus" :key="item.route" :index="item.route">{{item.label}}</el-menu-item></el-menu><button class="portal-return" @click="router.push('/portal')">← 返回统一门户</button></el-aside><el-container><el-header><div class="header-title"><b>{{system.name}}</b><span>{{system.description}}</span></div><div class="header-user"><el-tag effect="plain">{{auth.user?.positionName||'业务用户'}}</el-tag><span>{{auth.user?.realName}}</span><el-button link type="primary" @click="logout">退出</el-button></div></el-header><el-main><router-view/></el-main></el-container></el-container></template>
<style scoped>.system-shell{height:100vh;overflow:hidden}.system-shell>.el-aside{position:relative;height:100vh;box-sizing:border-box;overflow-y:auto;overflow-x:hidden;padding:18px 12px 70px;background:#14283e;color:#dce8f6;scrollbar-gutter:stable}.system-shell>.el-container{min-width:0;height:100vh;overflow:hidden}.system-brand{display:flex;align-items:center;gap:11px;padding:3px 10px 27px}.system-symbol{display:grid;place-items:center;width:36px;height:36px;flex:0 0 36px;border-radius:10px;background:var(--accent);color:#fff;font-weight:900}.system-brand b{display:block;color:#fff;font-size:18px}.system-brand small{display:block;margin-top:3px;color:#8ca6c0;font-size:10px}.nav-label{margin:10px 11px 7px;color:#7895b2;font-size:11px;letter-spacing:1px}.el-menu{border:0;background:transparent}.el-menu :deep(.el-menu-item){height:41px;margin:2px 0;border-radius:8px;color:#c4d4e5}.el-menu :deep(.el-menu-item:hover),.el-menu :deep(.el-menu-item.is-active){background:color-mix(in srgb,var(--accent) 25%,transparent);color:#fff}.portal-return{position:absolute;left:20px;bottom:20px;border:0;background:none;color:#8fa9c4;cursor:pointer}.portal-return:hover{color:#fff}.el-header{height:64px;flex:0 0 64px;display:flex;align-items:center;justify-content:space-between;padding:0 28px;border-bottom:1px solid #e8edf4;background:#fff}.header-title b{color:#273f5d}.header-title span{margin-left:13px;color:#96a4b4;font-size:11px}.header-user{display:flex;align-items:center;gap:11px;color:#50657d;font-size:13px}.el-main{height:calc(100vh - 64px);box-sizing:border-box;overflow-y:scroll;padding:25px 28px;background:#f3f6fa;scrollbar-gutter:stable}</style>
