<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import http from '../../api/http'
import TablePager from '../../shared/components/TablePager.vue'
import { zh } from '../../shared/display'
import { showErrorDialog } from '../../shared/errorDialog'
import { loadMdmUnits } from '../../shared/mdmOptions'
const rows=ref<any[]>([]),lines=ref<any[]>([]),loading=ref(false),drawer=ref(false),compareDialog=ref(false),keyword=ref(''),page=ref(1),size=ref(20),total=ref(0),compareRows=ref<any[]>([]),compare=reactive({code:'',left:'',right:''})
const unitLabels=ref(new Map<string,string>())
function unitLabel(value:unknown){return unitLabels.value.get(String(value??''))||zh(value)}
async function load(){loading.value=true;try{const{data}=await http.get('/plm/structures/boms',{params:{keyword:keyword.value||undefined,page:page.value,size:size.value}});rows.value=data.data.content;total.value=data.data.totalElements;if(!rows.value.length&&total.value>0&&page.value>1){page.value--;await load()}}catch(e:any){showErrorDialog(e?.message,'加载BOM副本失败')}finally{loading.value=false}}
function search(){page.value=1;void load()}async function detail(row:any){try{const{data}=await http.get(`/plm/structures/boms/${row.bom_code}/${row.bom_version}`);lines.value=data.data.lines;drawer.value=true}catch(e:any){showErrorDialog(e?.message,'读取BOM结构失败')}}function openCompare(row:any){Object.assign(compare,{code:row.bom_code,left:row.bom_version,right:''});compareRows.value=[];compareDialog.value=true}async function runCompare(){if(!compare.code||!compare.left||!compare.right)return showErrorDialog('请输入BOM编码和两个版本','表单校验失败');try{const{data}=await http.get('/plm/structures/boms/compare',{params:compare});compareRows.value=data.data||[]}catch(e:any){showErrorDialog(e?.message,'BOM版本比较失败')}}onMounted(async()=>{try{unitLabels.value=new Map((await loadMdmUnits()).map(unit=>[unit.value,unit.label]))}catch{}await load()})
</script>
<template><section class="bom-page"><div class="page-head"><div><span>工程结构管理</span><h1>工程物料清单（EBOM / MBOM）</h1><p>查看 MDM 审批发布到 PLM 的受控 BOM 副本，并比较版本用量差异。</p></div><el-button @click="load">刷新副本</el-button></div><el-card shadow="never"><div class="toolbar"><el-input v-model="keyword" clearable placeholder="BOM或产品编码" @keyup.enter="search"/><el-button @click="search">查询</el-button></div><el-table :data="rows" v-loading="loading" stripe><el-table-column prop="bom_code" label="BOM编码"/><el-table-column prop="bom_version" label="版本" width="90"/><el-table-column prop="product_code" label="产品编码"/><el-table-column prop="bom_type" label="类型" width="100"><template #default="{row}"><el-tag>{{zh(row.bom_type)}}</el-tag></template></el-table-column><el-table-column prop="effective_date" label="生效日期"><template #default="{row}">{{zh(row.effective_date)}}</template></el-table-column><el-table-column prop="master_version" label="主数据版本"/><el-table-column prop="synced_at" label="同步时间" min-width="170"><template #default="{row}">{{zh(row.synced_at)}}</template></el-table-column><el-table-column label="操作" width="140"><template #default="{row}"><el-button link type="primary" @click="detail(row)">结构</el-button><el-button link @click="openCompare(row)">版本比较</el-button></template></el-table-column></el-table><TablePager v-model:page="page" v-model:size="size" :total="total" :disabled="loading" @change="load"/></el-card><el-drawer v-model="drawer" title="BOM结构明细" size="720px"><el-table :data="lines" border><el-table-column prop="line_no" label="行号" width="70"/><el-table-column prop="child_material_code" label="子件物料编码"/><el-table-column prop="child_material_name" label="子件物料名称"/><el-table-column prop="qty_per" label="单位用量"/><el-table-column prop="unit_code" label="单位" width="75"><template #default="{row}">{{unitLabel(row.unit_code)}}</template></el-table-column><el-table-column prop="scrap_rate" label="损耗率"/></el-table></el-drawer><el-dialog v-model="compareDialog" title="BOM版本比较" width="820px"><div class="compare-bar"><el-input v-model="compare.code" placeholder="BOM编码"/><el-input v-model="compare.left" placeholder="原版本，如 V1.0"/><span>→</span><el-input v-model="compare.right" placeholder="新版本，如 V1.1"/><el-button type="primary" @click="runCompare">比较</el-button></div><el-table :data="compareRows" border><el-table-column prop="materialCode" label="物料编码"/><el-table-column prop="leftQty" label="原用量"/><el-table-column prop="rightQty" label="新用量"/><el-table-column prop="deltaQty" label="差异"/><el-table-column prop="changeType" label="变化类型"><template #default="{row}"><el-tag :type="row.changeType==='ADDED'?'success':row.changeType==='REMOVED'?'danger':row.changeType==='CHANGED'?'warning':'info'">{{zh(row.changeType)}}</el-tag></template></el-table-column></el-table></el-dialog></section></template>
<style scoped>.bom-page{max-width:1480px;margin:0 auto}.page-head{display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:17px}.page-head span{color:#3775d6;font-size:10px;font-weight:800;letter-spacing:1.4px}.page-head h1{margin:6px 0;color:#243d5d;font-size:25px}.page-head p{color:#8291a4;font-size:12px}.toolbar,.compare-bar{display:flex;align-items:center;gap:9px;margin-bottom:14px}.toolbar .el-input{width:280px}.compare-bar .el-input{width:180px}</style>
