<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import http from '../../api/http'
import TablePager from '../../shared/components/TablePager.vue'
import { zh } from '../../shared/display'
type Field={key:string;db:string;label:string;required?:boolean;type?:'select'|'date';options?:string[]}
const props=defineProps<{kind:string}>()
const configs:Record<string,{title:string;subtitle:string;releasable:boolean;fields:Field[]}>= {
 families:{title:'产品族',subtitle:'维护产品族、市场细分和产品负责人。',releasable:false,fields:[{key:'familyCode',db:'family_code',label:'产品族编码',required:true},{key:'familyName',db:'family_name',label:'产品族名称',required:true},{key:'marketSegment',db:'market_segment',label:'市场细分'},{key:'ownerUser',db:'owner_user',label:'负责人'},{key:'status',db:'status',label:'状态',type:'select',options:['ACTIVE','DISABLED']}]},
 versions:{title:'产品版本',subtitle:'维护产品工程版本、生命周期和生效日期。',releasable:true,fields:[{key:'productCode',db:'product_code',label:'产品编码',required:true},{key:'versionNo',db:'version_no',label:'版本号',required:true},{key:'versionName',db:'version_name',label:'版本名称'},{key:'lifecycleStatus',db:'lifecycle_status',label:'生命周期',type:'select',options:['DESIGN','TRIAL','MASS','PROD','EOL']},{key:'baselineNo',db:'baseline_no',label:'基线编号'},{key:'effectiveDate',db:'effective_date',label:'生效日期',type:'date'}]},
 documents:{title:'受控文档',subtitle:'管理图纸、工艺卡、作业指导书和文档版本。',releasable:true,fields:[{key:'docNo',db:'doc_no',label:'文档编号',required:true},{key:'docName',db:'doc_name',label:'文档名称',required:true},{key:'docType',db:'doc_type',label:'文档类型',required:true,type:'select',options:['DRAWING','PROCESS_CARD','WORK_INSTRUCTION','SPECIFICATION']},{key:'versionNo',db:'version_no',label:'版本号'},{key:'productCode',db:'product_code',label:'产品编码'},{key:'fileName',db:'file_name',label:'文件名'},{key:'confidentiality',db:'confidentiality',label:'密级',type:'select',options:['PUBLIC','INTERNAL','CONFIDENTIAL']}]},
 baselines:{title:'工程基线',subtitle:'冻结产品、BOM、工艺路线的可追溯版本组合。',releasable:true,fields:[{key:'baselineNo',db:'baseline_no',label:'基线编号',required:true},{key:'baselineName',db:'baseline_name',label:'基线名称',required:true},{key:'productCode',db:'product_code',label:'产品编码',required:true},{key:'productVersion',db:'product_version',label:'产品版本',required:true},{key:'bomCode',db:'bom_code',label:'BOM编码'},{key:'bomVersion',db:'bom_version',label:'BOM版本'},{key:'routingCode',db:'routing_code',label:'工艺路线'},{key:'routingVersion',db:'routing_version',label:'路线版本'}]}
}
const cfg=computed(()=>configs[props.kind]),rows=ref<any[]>([]),loading=ref(false),dialog=ref(false),saving=ref(false),editingId=ref<number|null>(null),keyword=ref(''),page=ref(1),size=ref(20),total=ref(0),form=reactive<any>({})
async function load(){loading.value=true;try{const{data}=await http.get(`/plm/catalog/${props.kind}`,{params:{keyword:keyword.value||undefined,page:page.value,size:size.value}});rows.value=data.data.content;total.value=data.data.totalElements;if(!rows.value.length&&total.value>0&&page.value>1){page.value--;await load()}}finally{loading.value=false}}
function search(){page.value=1;load()}function create(){editingId.value=null;Object.keys(form).forEach(k=>delete form[k]);for(const f of cfg.value.fields)form[f.key]=f.options?.[0]||'';dialog.value=true}function edit(row:any){editingId.value=row.id;for(const f of cfg.value.fields)form[f.key]=row[f.db];dialog.value=true}
async function save(){const miss=cfg.value.fields.find(f=>f.required&&!form[f.key]);if(miss)return ElMessage.warning(`请填写${miss.label}`);saving.value=true;try{if(editingId.value)await http.put(`/plm/catalog/${props.kind}/${editingId.value}`,form);else{await http.post(`/plm/catalog/${props.kind}`,form);page.value=1}ElMessage.success('保存成功');dialog.value=false;await load()}catch(e:any){ElMessage.error(e.message||'保存失败')}finally{saving.value=false}}
async function release(row:any){try{await http.post(`/plm/catalog/${props.kind}/${row.id}/release`);ElMessage.success('版本已受控发布');await load()}catch(e:any){ElMessage.error(e.message||'发布失败')}}watch(()=>props.kind,()=>{page.value=1;load()});onMounted(load)
</script>
<template><section class="catalog-page"><div class="page-head"><div><span>产品全生命周期受控数据</span><h1>{{cfg.title}}</h1><p>{{cfg.subtitle}}</p></div><el-button type="primary" @click="create">新增{{cfg.title}}</el-button></div><el-card shadow="never"><div class="toolbar"><el-input v-model="keyword" clearable placeholder="输入编码或名称" @keyup.enter="search"/><el-button @click="search">查询</el-button></div><el-table :data="rows" v-loading="loading" stripe><el-table-column v-for="f in cfg.fields" :key="f.db" :prop="f.db" :label="f.label" min-width="120"/><el-table-column prop="status" label="状态" width="105"><template #default="{row}"><el-tag :type="row.status==='RELEASED'||row.status==='ACTIVE'?'success':'info'">{{zh(row.status)}}</el-tag></template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="{row}"><el-button link type="primary" :disabled="row.status==='RELEASED'" @click="edit(row)">编辑</el-button><el-button v-if="cfg.releasable" link type="success" :disabled="row.status==='RELEASED'" @click="release(row)">发布</el-button></template></el-table-column></el-table><TablePager v-model:page="page" v-model:size="size" :total="total" :disabled="loading" @change="load"/></el-card><el-dialog v-model="dialog" :title="`${editingId?'编辑':'新增'}${cfg.title}`" width="760px"><el-form label-position="top"><el-row :gutter="16"><el-col v-for="f in cfg.fields" :key="f.key" :span="12"><el-form-item :label="f.label" :required="f.required"><el-select v-if="f.type==='select'" v-model="form[f.key]" style="width:100%"><el-option v-for="o in f.options" :key="o" :label="zh(o)" :value="o"/></el-select><el-date-picker v-else-if="f.type==='date'" v-model="form[f.key]" value-format="YYYY-MM-DD" style="width:100%"/><el-input v-else v-model="form[f.key]" :disabled="Boolean(editingId)&&(f.key.endsWith('Code')||f.key.endsWith('No'))"/></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog></section></template>
<style scoped>.catalog-page{max-width:1480px;margin:0 auto}.page-head{display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:17px}.page-head span{color:#3775d6;font-size:10px;font-weight:800;letter-spacing:1.4px}.page-head h1{margin:6px 0;color:#243d5d;font-size:25px}.page-head p{color:#8291a4;font-size:12px}.toolbar{display:flex;gap:8px;margin-bottom:14px}.toolbar .el-input{width:280px}</style>
