package com.mfg.mdm.service;
import com.fasterxml.jackson.databind.ObjectMapper;import com.mfg.common.exception.BizException;import com.mfg.mdm.domain.*;import com.mfg.mdm.repo.*;import lombok.RequiredArgsConstructor;import lombok.extern.slf4j.Slf4j;import org.springframework.data.domain.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.LocalDateTime;import java.util.*;
@Slf4j @Service @RequiredArgsConstructor public class MdmOutboxService{private final JdbcTemplate jdbc;private final ObjectMapper json;private final MasterDataDistributor distributor;private final CustomerRepository customers;private final SupplierRepository suppliers;private final MaterialRepository materials;private final ProductRepository products;private final BomRepository boms;private final RoutingRepository routings;
 @Transactional public void enqueue(MasterDataEntity e){enqueueEvent(e,"PUBLISHED");}
 @Transactional public void enqueueDisabled(MasterDataEntity e){enqueueEvent(e,"DISABLED");}
 private void enqueueEvent(MasterDataEntity e,String action){String eventId=UUID.randomUUID().toString();String payload;try{payload=json.writeValueAsString(Map.of("code",e.getBusinessCode(),"version",e.getVersionNo(),"status",e.getStatus()));}catch(Exception ex){payload="{}";}jdbc.update("INSERT INTO src_mdm.md_outbox(event_id,event_type,aggregate_type,aggregate_id,aggregate_code,aggregate_version,payload) VALUES(?,?,?,?,?,?,CAST(? AS JSON))",eventId,e.bizType().name()+"."+action,e.bizType().name(),e.getId(),e.getBusinessCode(),e.getVersionNo(),payload);for(String target:e.bizType().systemArray())jdbc.update("INSERT IGNORE INTO src_mdm.md_inbox(event_id,target_system) VALUES(?,?)",eventId,target.trim());}
 @Scheduled(fixedDelay=1000) public void dispatch(){for(Map<String,Object> row:jdbc.queryForList("SELECT * FROM src_mdm.md_outbox WHERE status IN ('PENDING','RETRYING') AND retry_count<3 ORDER BY occurred_at LIMIT 20")){try{process(String.valueOf(row.get("event_id")));}catch(Exception e){log.warn("Outbox处理失败: {}",e.getMessage());}}}
 @Transactional public void process(String eventId){Map<String,Object> event=jdbc.queryForMap("SELECT * FROM src_mdm.md_outbox WHERE event_id=? FOR UPDATE",eventId);jdbc.update("UPDATE src_mdm.md_outbox SET status='PROCESSING' WHERE event_id=?",eventId);MasterDataEntity entity=resolve(String.valueOf(event.get("aggregate_type")),((Number)event.get("aggregate_id")).longValue());boolean all=true;String error=null;for(Map<String,Object> inbox:jdbc.queryForList("SELECT * FROM src_mdm.md_inbox WHERE event_id=? AND status<>'SUCCESS'",eventId)){String target=String.valueOf(inbox.get("target_system"));var result=distributor.distributeTo(entity,target);if(result.success()){jdbc.update("UPDATE src_mdm.md_inbox SET status='SUCCESS',processed_at=NOW(3),error_message=NULL WHERE id=?",inbox.get("id"));reconcile(eventId,target,entity,result.rows());}else{all=false;error=result.error();jdbc.update("UPDATE src_mdm.md_inbox SET status='FAILED',retry_count=retry_count+1,error_message=? WHERE id=?",cut(error),inbox.get("id"));}}if(all)jdbc.update("UPDATE src_mdm.md_outbox SET status='SUCCESS',processed_at=NOW(3),error_message=NULL WHERE event_id=?",eventId);else jdbc.update("UPDATE src_mdm.md_outbox SET status=IF(retry_count+1>=3,'DEAD','RETRYING'),retry_count=retry_count+1,error_message=? WHERE event_id=?",cut(error),eventId);}
 @Transactional public void retry(String eventId){jdbc.update("UPDATE src_mdm.md_outbox SET status='RETRYING',retry_count=0,error_message=NULL WHERE event_id=?",eventId);jdbc.update("UPDATE src_mdm.md_inbox SET status='PENDING',retry_count=0,error_message=NULL WHERE event_id=? AND status<>'SUCCESS'",eventId);}
 @Transactional(readOnly=true)public Page<Map<String,Object>> page(String status,int page,int size){int p=Math.max(0,page-1),s=Math.min(200,Math.max(1,size));String w=status==null||status.isBlank()?"":" WHERE status=?";Object[] args=status==null||status.isBlank()?new Object[]{}:new Object[]{status};Long t=jdbc.queryForObject("SELECT COUNT(*) FROM src_mdm.md_outbox"+w,Long.class,args);List<Object>a=new ArrayList<>(Arrays.asList(args));a.add(s);a.add(p*s);return new PageImpl<>(jdbc.queryForList("SELECT * FROM src_mdm.md_outbox"+w+" ORDER BY occurred_at DESC LIMIT ? OFFSET ?",a.toArray()),PageRequest.of(p,s),t==null?0:t);}
 @Transactional(readOnly=true)public Map<String,Object> detail(String id){Map<String,Object> x=new LinkedHashMap<>(jdbc.queryForMap("SELECT * FROM src_mdm.md_outbox WHERE event_id=?",id));x.put("targets",jdbc.queryForList("SELECT * FROM src_mdm.md_inbox WHERE event_id=? ORDER BY target_system",id));x.put("reconciliations",jdbc.queryForList("SELECT * FROM src_mdm.md_reconciliation WHERE event_id=? ORDER BY checked_at DESC",id));return x;}
 @Transactional public Map<String,Object> reconcileEvent(String id){Map<String,Object> event=jdbc.queryForMap("SELECT * FROM src_mdm.md_outbox WHERE event_id=?",id);MasterDataEntity e=resolve(String.valueOf(event.get("aggregate_type")),((Number)event.get("aggregate_id")).longValue());for(Map<String,Object> t:jdbc.queryForList("SELECT target_system FROM src_mdm.md_inbox WHERE event_id=?",id))reconcile(id,String.valueOf(t.get("target_system")),e,0);return detail(id);}
 private void reconcile(String eventId,String target,MasterDataEntity e,int rows){String result=rows>0?"MATCH":"CHECK";jdbc.update("INSERT INTO src_mdm.md_reconciliation(event_id,target_system,entity_code,source_version,target_version,result,message) VALUES(?,?,?,?,?,?,?)",eventId,target,e.getBusinessCode(),e.getVersionNo(),rows>0?e.getVersionNo():null,result,rows>0?"编码与版本已写入目标系统":"目标系统未返回写入行数，请人工核查");}
 private MasterDataEntity resolve(String type,Long id){return switch(type){case"CUSTOMER"->customers.findById(id).orElseThrow();case"SUPPLIER"->suppliers.findById(id).orElseThrow();case"MATERIAL"->materials.findById(id).orElseThrow();case"PRODUCT"->products.findById(id).orElseThrow();case"BOM"->boms.findById(id).orElseThrow();case"ROUTING"->routings.findById(id).orElseThrow();default->throw BizException.conflict("不支持的Outbox聚合类型: "+type);};}private String cut(String s){return s==null?null:s.substring(0,Math.min(490,s.length()));}}
