package com.mfg.mdm.service;
import com.mfg.common.api.ErrorCode;import com.mfg.common.exception.BizException;import com.mfg.mdm.dto.RoutingCommand;import com.mfg.mdm.entity.*;import com.mfg.mdm.repo.*;import com.mfg.security.config.CurrentUser;import com.mfg.workflow.entity.WfInstance;import lombok.RequiredArgsConstructor;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;import java.time.LocalDate;
@Service @RequiredArgsConstructor public class RoutingService{private final RoutingRepository routings;private final RoutingOperationRepository operations;private final ProductRepository products;private final MasterDataService master;
 @Transactional public Routing create(RoutingCommand c){String v=version(c);if(routings.existsByRoutingCodeAndRoutingVersion(c.routingCode(),v))throw BizException.of(ErrorCode.MASTER_DATA_ALREADY_EXISTS,"工艺路线编码与版本已存在");validateProduct(c.productCode());Routing r=new Routing();copy(c,r);r.setCreatedBy(CurrentUser.usernameOrSystem());r=master.create(r,routings);saveOps(r.getId(),c);return detail(r.getId());}
 @Transactional public Routing update(Long id,RoutingCommand c){Routing r=load(id);validateProduct(c.productCode());copy(c,r);master.update(r,routings,c.changeReason());operations.deleteByRoutingId(id);saveOps(id,c);return detail(id);}
 @Transactional public WfInstance submit(Long id){Routing r=detail(id);if(r.getOperations().isEmpty())throw BizException.of(ErrorCode.MASTER_DATA_INVALID_STATE,"工艺路线至少包含一道工序");return master.submitForApproval(r,routings);}
 @Transactional(readOnly=true) public Routing detail(Long id){Routing r=load(id);r.setOperations(operations.findByRoutingIdOrderByOpSeqAsc(id));return r;}
 private Routing load(Long id){return routings.findById(id).orElseThrow(()->BizException.notFound("工艺路线",id));}private String version(RoutingCommand c){return c.routingVersion()==null||c.routingVersion().isBlank()?"V1.0":c.routingVersion();}
 private void validateProduct(String code){Product p=products.findByProductCode(code).orElseThrow(()->BizException.of(ErrorCode.MASTER_DATA_NOT_FOUND,"产品不存在："+code));master.assertConsumable(p,"工艺路线");}
 private void copy(RoutingCommand c,Routing r){r.setRoutingCode(c.routingCode());r.setRoutingName(c.routingName());r.setProductCode(c.productCode());r.setRoutingVersion(version(c));r.setEffectiveDate(c.effectiveDate()==null?LocalDate.now():c.effectiveDate());r.setExpireDate(c.expireDate());r.setChangeReason(c.changeReason());}
 private void saveOps(Long id,RoutingCommand c){for(var x:c.operations()){RoutingOperation o=new RoutingOperation();o.setRoutingId(id);o.setOpSeq(x.opSeq());o.setOperationCode(x.operationCode());o.setOperationName(x.operationName());o.setWorkCenter(x.workCenter());o.setSetupTimeMin(x.setupTimeMin()==null?BigDecimal.ZERO:x.setupTimeMin());o.setRunTimeMin(x.runTimeMin()==null?BigDecimal.ZERO:x.runTimeMin());o.setWaitTimeMin(x.waitTimeMin()==null?BigDecimal.ZERO:x.waitTimeMin());o.setDefaultEquipmentCode(x.defaultEquipmentCode());o.setRequiredSkill(x.requiredSkill());o.setKeyOperation(Boolean.TRUE.equals(x.keyOperation()));o.setInspectionOp(Boolean.TRUE.equals(x.inspectionOp()));o.setInspectionRequired(Boolean.TRUE.equals(x.inspectionRequired()));o.setRemark(x.remark());operations.save(o);}}
}
