package com.mfg.mdm.controller;
import com.mfg.common.api.*;import com.mfg.common.exception.BizException;import com.mfg.mdm.entity.*;import com.mfg.mdm.repo.*;import com.mfg.mdm.service.MasterDataService;import com.mfg.workflow.entity.WfInstance;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.*;import org.springframework.web.bind.annotation.*;
/** 客户、供应商必须在 MDM 建立并审批发布，CRM/ERP/SRM 只消费副本。 */
@RestController @RequestMapping("/api/mdm") @RequiredArgsConstructor public class PartnerMasterController{private final CustomerRepository customers;private final SupplierRepository suppliers;private final MasterDataService master;
 @GetMapping("/customers")public ApiResponse<Page<Customer>> customers(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size){return ApiResponse.ok(customers.findAll(PageRequest.of(Math.max(0,page-1),Math.min(200,size))));}
 @PostMapping("/customers")public ApiResponse<Customer> createCustomer(@RequestBody Customer c){if(customers.existsByCustomerCode(c.getCustomerCode()))throw BizException.of(ErrorCode.MASTER_DATA_ALREADY_EXISTS,"客户编码已存在");return ApiResponse.ok(master.create(c,customers));}
 @PostMapping("/customers/{id}/submit")public ApiResponse<WfInstance> submitCustomer(@PathVariable Long id){Customer c=customers.findById(id).orElseThrow(()->BizException.notFound("客户",id));return ApiResponse.ok(master.submitForApproval(c,customers));}
 @GetMapping("/suppliers")public ApiResponse<Page<Supplier>> suppliers(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size){return ApiResponse.ok(suppliers.findAll(PageRequest.of(Math.max(0,page-1),Math.min(200,size))));}
 @PostMapping("/suppliers")public ApiResponse<Supplier> createSupplier(@RequestBody Supplier s){if(suppliers.existsBySupplierCode(s.getSupplierCode()))throw BizException.of(ErrorCode.MASTER_DATA_ALREADY_EXISTS,"供应商编码已存在");return ApiResponse.ok(master.create(s,suppliers));}
 @PostMapping("/suppliers/{id}/submit")public ApiResponse<WfInstance> submitSupplier(@PathVariable Long id){Supplier s=suppliers.findById(id).orElseThrow(()->BizException.notFound("供应商",id));return ApiResponse.ok(master.submitForApproval(s,suppliers));}}
