package com.mfg.mdm.controller;
import com.mfg.common.api.*;import com.mfg.common.exception.BizException;import com.mfg.mdm.entity.*;import com.mfg.mdm.repo.*;import com.mfg.mdm.service.MasterDataService;import com.mfg.workflow.entity.WfInstance;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.*;import org.springframework.web.bind.annotation.*;
/** 客户、供应商必须在 MDM 建立并审批发布，CRM/ERP/SRM 只消费副本。 */
@RestController @RequestMapping("/api/mdm") @RequiredArgsConstructor public class PartnerMasterController{private final CustomerRepository customers;private final SupplierRepository suppliers;private final MasterDataService master;
 @GetMapping("/customers")public ApiResponse<Page<Customer>> customers(@RequestParam(required=false)String keyword,@RequestParam(required=false)String status,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size){var p=PageRequest.of(Math.max(0,page-1),Math.min(200,Math.max(1,size)));return ApiResponse.ok(status!=null&&!status.isBlank()?customers.findByStatus(status,p):keyword!=null&&!keyword.isBlank()?customers.findByCustomerNameContainingOrCustomerCodeContaining(keyword,keyword,p):customers.findAll(p));}
 @PostMapping("/customers")public ApiResponse<Customer> createCustomer(@RequestBody Customer c){if(customers.existsByCustomerCode(c.getCustomerCode()))throw BizException.of(ErrorCode.MASTER_DATA_ALREADY_EXISTS,"客户编码已存在");return ApiResponse.ok(master.create(c,customers));}
 @PostMapping("/customers/{id}/submit")public ApiResponse<WfInstance> submitCustomer(@PathVariable Long id){Customer c=customers.findById(id).orElseThrow(()->BizException.notFound("客户",id));return ApiResponse.ok(master.submitForApproval(c,customers));}
 @GetMapping("/customers/{id}")public ApiResponse<Customer>customer(@PathVariable Long id){return ApiResponse.ok(customers.findById(id).orElseThrow(()->BizException.notFound("客户",id)));}@PutMapping("/customers/{id}")public ApiResponse<Customer>updateCustomer(@PathVariable Long id,@RequestBody Customer x){Customer c=customers.findById(id).orElseThrow(()->BizException.notFound("客户",id));c.setCustomerName(x.getCustomerName());c.setShortName(x.getShortName());c.setUnifiedSocialCode(x.getUnifiedSocialCode());c.setCustomerLevel(x.getCustomerLevel());c.setCustomerType(x.getCustomerType());c.setIndustry(x.getIndustry());c.setRegion(x.getRegion());c.setCreditLimit(x.getCreditLimit());c.setPaymentTerms(x.getPaymentTerms());c.setTaxNo(x.getTaxNo());c.setAddress(x.getAddress());return ApiResponse.ok(master.update(c,customers,x.getChangeReason()));}@DeleteMapping("/customers/{id}")public ApiResponse<Void>disableCustomer(@PathVariable Long id){Customer c=customers.findById(id).orElseThrow(()->BizException.notFound("客户",id));c.setStatus("DISABLED");customers.save(c);return ApiResponse.ok();}
 @GetMapping("/suppliers")public ApiResponse<Page<Supplier>> suppliers(@RequestParam(required=false)String keyword,@RequestParam(required=false)String status,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size){var p=PageRequest.of(Math.max(0,page-1),Math.min(200,Math.max(1,size)));return ApiResponse.ok(status!=null&&!status.isBlank()?suppliers.findByStatus(status,p):keyword!=null&&!keyword.isBlank()?suppliers.findBySupplierNameContainingOrSupplierCodeContaining(keyword,keyword,p):suppliers.findAll(p));}
 @PostMapping("/suppliers")public ApiResponse<Supplier> createSupplier(@RequestBody Supplier s){if(suppliers.existsBySupplierCode(s.getSupplierCode()))throw BizException.of(ErrorCode.MASTER_DATA_ALREADY_EXISTS,"供应商编码已存在");return ApiResponse.ok(master.create(s,suppliers));}
 @PostMapping("/suppliers/{id}/submit")public ApiResponse<WfInstance> submitSupplier(@PathVariable Long id){Supplier s=suppliers.findById(id).orElseThrow(()->BizException.notFound("供应商",id));return ApiResponse.ok(master.submitForApproval(s,suppliers));}@GetMapping("/suppliers/{id}")public ApiResponse<Supplier>supplier(@PathVariable Long id){return ApiResponse.ok(suppliers.findById(id).orElseThrow(()->BizException.notFound("供应商",id)));}@PutMapping("/suppliers/{id}")public ApiResponse<Supplier>updateSupplier(@PathVariable Long id,@RequestBody Supplier x){Supplier s=suppliers.findById(id).orElseThrow(()->BizException.notFound("供应商",id));s.setSupplierName(x.getSupplierName());s.setShortName(x.getShortName());s.setUnifiedSocialCode(x.getUnifiedSocialCode());s.setSupplierLevel(x.getSupplierLevel());s.setSupplierType(x.getSupplierType());s.setLeadTimeDays(x.getLeadTimeDays());s.setSupplyCategory(x.getSupplyCategory());s.setQualStatus(x.getQualStatus());s.setQualExpireDate(x.getQualExpireDate());s.setPaymentTerms(x.getPaymentTerms());s.setTaxNo(x.getTaxNo());return ApiResponse.ok(master.update(s,suppliers,x.getChangeReason()));}@DeleteMapping("/suppliers/{id}")public ApiResponse<Void>disableSupplier(@PathVariable Long id){Supplier s=suppliers.findById(id).orElseThrow(()->BizException.notFound("供应商",id));s.setStatus("DISABLED");suppliers.save(s);return ApiResponse.ok();}}
