export type P3Field={key:string;label:string;type?:'text'|'number'|'date'|'textarea'|'select';required?:boolean;options?:{label:string,value:string}[]}
export type P3Config={fields:P3Field[];columns:string[];statuses?:{label:string,value:string}[];readonly?:boolean}
const s=(...x:string[])=>x.map(v=>{const[a,b]=v.split(':');return{label:a,value:b||a}})
export const p3Catalog:Record<string,P3Config>={
'srm:onboarding':{columns:['application_no','supplier_name','category_code','contact_name','risk_level','status','created_at'],fields:[{key:'applicationNo',label:'申请编号',required:true},{key:'supplierName',label:'供应商名称',required:true},{key:'categoryCode',label:'供应品类'},{key:'contactName',label:'联系人'},{key:'contactPhone',label:'联系电话'},{key:'riskLevel',label:'风险等级',type:'select',options:s('低:LOW','中:MEDIUM','高:HIGH')}],statuses:s('提交审批:APPROVING','批准:APPROVED','认证:CERTIFIED','驳回:REJECTED','加入黑名单:BLACKLISTED')},
'srm:rfqs':{columns:['rfq_no','title','material_code','quantity','required_date','winner_supplier_code','status'],fields:[{key:'rfqNo',label:'询价单号',required:true},{key:'title',label:'询价主题',required:true},{key:'materialCode',label:'物料编码',required:true},{key:'quantity',label:'需求数量',type:'number',required:true},{key:'requiredDate',label:'需求日期',type:'date',required:true},{key:'sourceRequisitionNo',label:'采购申请单号'}],statuses:s('发布:PUBLISHED','开始报价:QUOTING','截标:CLOSED','取消:CANCELLED')},
'srm:purchase-orders':{columns:['purchase_order_no','supplier_code','material_code','order_qty','received_qty','unit_price','total_amount','expected_date','order_status'],fields:[],readonly:true},
'srm:asns':{columns:['asn_no','purchase_order_no','supplier_code','material_code','batch_no','ship_qty','expected_arrival_date','status'],fields:[{key:'asnNo',label:'ASN编号',required:true},{key:'purchaseOrderNo',label:'采购订单号',required:true},{key:'supplierCode',label:'供应商编码',required:true},{key:'materialCode',label:'物料编码',required:true},{key:'batchNo',label:'供应商批次'},{key:'shipQty',label:'发运数量',type:'number',required:true},{key:'shipDate',label:'发运日期',type:'date'},{key:'expectedArrivalDate',label:'预计到货日期',type:'date'}],statuses:s('发运:SHIPPED','取消:CANCELLED')},
'srm:supplier-quality':{columns:['issue_no','supplier_code','source_no','defect_qty','ppm','eight_d_status','due_date'],fields:[{key:'issueNo',label:'问题编号',required:true},{key:'supplierCode',label:'供应商编码',required:true},{key:'sourceNo',label:'来源单号'},{key:'problemDesc',label:'问题描述',type:'textarea'},{key:'dueDate',label:'整改期限',type:'date'}],statuses:s('要求8D:EIGHT_D_REQUIRED','验证:VERIFYING','关闭:CLOSED')},
'srm:performance':{columns:['supplier_code','period_code','delivery_rate','qualified_rate','ppm','score','rating'],fields:[],readonly:true},
'wms:receipts':{columns:['receipt_no','asn_no','purchase_order_no','supplier_code','material_code','batch_no','received_qty','warehouse_code','status','inspection_no'],fields:[],readonly:true},
'wms:putaway':{columns:['putaway_no','receipt_no','material_code','batch_no','quantity','suggested_location','actual_location','status'],fields:[{key:'putawayNo',label:'上架单号',required:true},{key:'receiptNo',label:'收货单号',required:true},{key:'materialCode',label:'物料编码',required:true},{key:'batchNo',label:'批次'},{key:'quantity',label:'数量',type:'number',required:true},{key:'suggestedLocation',label:'推荐库位'},{key:'actualLocation',label:'实际库位'}],statuses:s('开始上架:PROCESSING','完成上架:COMPLETED','取消:CANCELLED')},
'wms:inventories':{columns:['material_code','warehouse_code','location_code','batch_no','on_hand_qty','allocated_qty','available_qty','frozen_qty','quality_status'],fields:[],readonly:true},
'wms:inventory-actions':{columns:['action_no','action_type','material_code','warehouse_code','location_code','batch_no','quantity','source_no','operator','created_at'],fields:[{key:'actionNo',label:'作业编号',required:true},{key:'actionType',label:'作业类型',type:'select',required:true,options:s('冻结:FREEZE','解冻:UNFREEZE','隔离:QUARANTINE','报废:SCRAP','退供:RETURN','领料:ISSUE','退料:RETURN_MATERIAL')},{key:'materialCode',label:'物料编码',required:true},{key:'warehouseCode',label:'仓库编码',required:true},{key:'locationCode',label:'库位编码'},{key:'batchNo',label:'批次'},{key:'quantity',label:'数量',type:'number',required:true},{key:'reason',label:'作业原因',type:'textarea'},{key:'sourceNo',label:'来源单号'}]},
'wms:transfers':{columns:['transfer_no','material_code','batch_no','quantity','from_warehouse','from_location','to_warehouse','to_location','status'],fields:[{key:'transferNo',label:'调拨单号',required:true},{key:'materialCode',label:'物料编码',required:true},{key:'batchNo',label:'批次'},{key:'quantity',label:'调拨数量',type:'number',required:true},{key:'fromWarehouse',label:'调出仓库',required:true},{key:'fromLocation',label:'调出库位'},{key:'toWarehouse',label:'调入仓库',required:true},{key:'toLocation',label:'调入库位'}],statuses:s('确认:CONFIRMED','执行:PROCESSING','完成:COMPLETED','取消:CANCELLED')},
'wms:counts':{columns:['count_no','warehouse_code','scope_type','planned_date','status','created_by'],fields:[{key:'countNo',label:'盘点单号',required:true},{key:'warehouseCode',label:'仓库编码',required:true},{key:'scopeType',label:'盘点范围',type:'select',options:s('全库:FULL','库区:ZONE','物料:MATERIAL','循环盘点:CYCLE')},{key:'plannedDate',label:'计划日期',type:'date'}],statuses:s('下达:RELEASED','盘点中:COUNTING','差异复核:REVIEWING','完成:COMPLETED','取消:CANCELLED')},
'qms:standards':{columns:['standard_code','standard_name','inspection_type','material_code','version_no','status'],fields:[{key:'standardCode',label:'标准编码',required:true},{key:'standardName',label:'标准名称',required:true},{key:'inspectionType',label:'检验类型',type:'select',options:s('来料检验:IQC','过程检验:IPQC','完工检验:FQC','出货检验:OQC')},{key:'materialCode',label:'物料编码'},{key:'versionNo',label:'版本号'}],statuses:s('发布:PUBLISHED','停用:DISABLED')},
'qms:sampling-plans':{columns:['plan_code','plan_name','aql_level','lot_size_min','lot_size_max','sample_size','accept_qty','reject_qty','status'],fields:[{key:'planCode',label:'方案编码',required:true},{key:'planName',label:'方案名称',required:true},{key:'aqlLevel',label:'AQL等级'},{key:'lotSizeMin',label:'最小批量',type:'number'},{key:'lotSizeMax',label:'最大批量',type:'number'},{key:'sampleSize',label:'抽样数量',type:'number'},{key:'acceptQty',label:'接收数',type:'number'},{key:'rejectQty',label:'拒收数',type:'number'}],statuses:s('启用:ENABLED','停用:DISABLED')},
'qms:inspections':{columns:['inspection_no','inspection_type','source_no','material_code','batch_no','supplier_code','inspected_qty','qualified_qty','defect_qty','inspect_result'],fields:[{key:'inspectionNo',label:'检验单号',required:true},{key:'inspectionType',label:'检验类型',type:'select',options:s('来料检验:IQC','过程检验:IPQC','完工检验:FQC','出货检验:OQC')},{key:'materialCode',label:'物料编码',required:true},{key:'batchNo',label:'批次'},{key:'inspectedQty',label:'送检数量',type:'number',required:true}]},
'qms:ncrs':{columns:['ncr_no','inspection_no','source_no','material_code','supplier_code','defect_qty','severity','responsible_dept','status','disposition'],fields:[],statuses:s('评审:REVIEWING','返工:REWORK','报废:SCRAPPED','让步:CONCESSION','退供:RETURNED','关闭:CLOSED')},
'qms:reworks':{columns:['rework_no','defect_no','material_code','rework_qty','qualified_qty','scrap_qty','rework_status'],fields:[],readonly:true},
'qms:capas':{columns:['capa_no','ncr_no','root_cause','corrective_action','preventive_action','owner_user','due_date','status'],fields:[{key:'capaNo',label:'CAPA编号',required:true},{key:'ncrNo',label:'NCR编号',required:true},{key:'rootCause',label:'根本原因',type:'textarea'},{key:'correctiveAction',label:'纠正措施',type:'textarea'},{key:'preventiveAction',label:'预防措施',type:'textarea'},{key:'ownerUser',label:'负责人'},{key:'dueDate',label:'完成期限',type:'date'}],statuses:s('执行中:IMPLEMENTING','待验证:VERIFYING','关闭:CLOSED')},
'qms:8d':{columns:['eight_d_no','ncr_no','supplier_code','problem_desc','root_cause','due_date','status'],fields:[{key:'eightDNo',label:'8D编号',required:true},{key:'ncrNo',label:'NCR编号',required:true},{key:'supplierCode',label:'供应商编码',required:true},{key:'teamMembers',label:'小组成员'},{key:'problemDesc',label:'问题描述',type:'textarea'},{key:'dueDate',label:'回复期限',type:'date'}],statuses:s('提交:SUBMITTED','验证:VERIFYING','关闭:CLOSED')}
}
