<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage } from 'element-plus'
import { systems } from '../../shared/systemCatalog'
import { useAuthStore } from '../../stores/auth'
const auth=useAuthStore();const visible=computed(()=>systems.filter(item=>auth.canAccess(item.code)))
const route=useRoute();onMounted(()=>{if(route.query.denied)ElMessage.warning('当前账号没有该页面或业务系统的访问权限')})
const open=(path:string)=>window.open(path,'_blank','noopener,noreferrer')
</script>
<template><section class="portal-home"><div class="welcome"><div><span>ENTERPRISE APPLICATION PORTAL</span><h1>欢迎回来，{{auth.user?.realName}}</h1><p>从统一门户进入已授权的业务系统。系统将在新标签页打开，共享当前登录状态。</p></div><div class="identity"><small>当前身份</small><b>{{auth.user?.positionName||auth.user?.username}}</b><span>{{auth.user?.roleNames?.join(' · ')||auth.user?.roles?.join(' · ')}}</span></div></div><div class="section-title"><div><h2>业务系统</h2><p>你当前可以访问 {{visible.length}} 个系统</p></div><el-tag type="success" effect="light">统一身份已生效</el-tag></div><div class="system-grid"><article v-for="item in visible" :key="item.code" class="system-card" :style="{'--accent':item.accent}" @click="open(item.route)"><div class="card-top"><div class="system-icon">{{item.shortName.slice(0,1)}}</div><span>{{item.shortName}}</span></div><h3>{{item.name}}</h3><p>{{item.description}}</p><div class="tags"><i v-for="tag in item.capabilities" :key="tag">{{tag}}</i></div><button>新标签页进入 <b>→</b></button></article></div><el-empty v-if="!visible.length" description="当前账号尚未分配业务系统，请联系管理员。"/></section></template>
<style scoped>.portal-home{max-width:1500px;margin:0 auto}.welcome{display:flex;justify-content:space-between;align-items:center;padding:27px 31px;border-radius:17px;background:linear-gradient(120deg,#173f71,#12253e);color:#fff}.welcome>div:first-child>span{font-size:10px;letter-spacing:1.5px;color:#83baff}.welcome h1{margin:9px 0 7px;font-size:27px}.welcome p{color:#b8c9dc;font-size:13px}.identity{min-width:230px;padding:14px 17px;border:1px solid rgba(255,255,255,.12);border-radius:11px;background:rgba(255,255,255,.06)}.identity small,.identity b,.identity span{display:block}.identity small{color:#8ba8c8}.identity b{margin:6px 0}.identity span{color:#9fb4cb;font-size:11px}.section-title{display:flex;align-items:center;justify-content:space-between;margin:23px 2px 13px}.section-title h2{color:#253d5c;font-size:18px}.section-title p{margin-top:4px;color:#8b9aab;font-size:11px}.system-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:15px}.system-card{position:relative;min-height:238px;padding:20px;border:1px solid #e2e8f0;border-radius:14px;background:#fff;cursor:pointer;transition:.2s}.system-card:hover{transform:translateY(-3px);border-color:color-mix(in srgb,var(--accent) 55%,#fff);box-shadow:0 13px 30px rgba(34,65,103,.11)}.card-top{display:flex;align-items:center;gap:9px;color:var(--accent);font-size:11px;font-weight:800;letter-spacing:.8px}.system-icon{display:grid;place-items:center;width:34px;height:34px;border-radius:9px;background:color-mix(in srgb,var(--accent) 12%,#fff);font-size:16px}.system-card h3{margin:16px 0 8px;color:#2a405c;font-size:17px}.system-card p{height:42px;color:#7d8da1;font-size:12px;line-height:1.65}.tags{display:flex;gap:5px;flex-wrap:wrap;margin-top:13px}.tags i{padding:4px 7px;border-radius:5px;background:#f2f5f9;color:#6c7d91;font-size:10px;font-style:normal}.system-card button{position:absolute;left:20px;right:20px;bottom:16px;padding-top:12px;border:0;border-top:1px solid #edf1f5;background:none;color:var(--accent);text-align:left;cursor:pointer}.system-card button b{float:right}@media(max-width:1300px){.system-grid{grid-template-columns:repeat(3,1fr)}}</style>
