package com.mfg.eam.controller;import com.mfg.common.api.*;import com.mfg.common.exception.BizException;import com.mfg.eam.entity.*;import com.mfg.eam.repo.*;import com.mfg.security.config.CurrentUser;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.*;import org.springframework.web.bind.annotation.*;import java.time.LocalDateTime;
@RestController @RequestMapping("/api/eam") @RequiredArgsConstructor public class EquipmentController{private final EquipmentRepository equipments;private final EquipmentFaultRepository faults;private final EquipmentInspectionRepository inspections;
 @GetMapping("/equipments")public ApiResponse<Page<Equipment>> equipmentPage(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size){return ApiResponse.ok(equipments.findAll(PageRequest.of(Math.max(0,page-1),Math.min(size,200))));}
 @PostMapping("/equipments")public ApiResponse<Equipment> createEquipment(@RequestBody Equipment e){if(equipments.existsByEquipmentCode(e.getEquipmentCode()))throw BizException.of(ErrorCode.MASTER_DATA_ALREADY_EXISTS,"设备编码已存在");e.setStatus("IDLE");return ApiResponse.ok(equipments.save(e));}
 @PostMapping("/equipments/{id}/status")public ApiResponse<Equipment> status(@PathVariable Long id,@RequestParam String status){if(!java.util.Set.of("RUNNING","IDLE","FAULT","MAINTENANCE","SCRAPPED").contains(status))throw BizException.of(ErrorCode.MASTER_DATA_INVALID_STATE,"非法设备状态");Equipment e=equipments.findById(id).orElseThrow(()->BizException.notFound("设备",id));e.setStatus(status);return ApiResponse.ok(equipments.save(e));}
 @GetMapping("/faults")public ApiResponse<Page<EquipmentFault>> faultPage(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size){return ApiResponse.ok(faults.findAll(PageRequest.of(Math.max(0,page-1),Math.min(size,200))));}
 @PostMapping("/faults")public ApiResponse<EquipmentFault> fault(@RequestBody EquipmentFault f){if(faults.existsByFaultNo(f.getFaultNo()))throw BizException.of(ErrorCode.MASTER_DATA_ALREADY_EXISTS,"故障单号已存在");Equipment e=equipments.findByEquipmentCode(f.getEquipmentCode()).orElseThrow(()->BizException.of(ErrorCode.MASTER_DATA_NOT_FOUND,"设备不存在"));f.setEquipmentName(e.getEquipmentName());f.setFaultTime(LocalDateTime.now());f.setReportedBy(CurrentUser.usernameOrSystem());f.setStatus("OPEN");e.setStatus("FAULT");equipments.save(e);return ApiResponse.ok(faults.save(f));}
 @PostMapping("/faults/{id}/close")public ApiResponse<EquipmentFault> close(@PathVariable Long id){EquipmentFault f=faults.findById(id).orElseThrow(()->BizException.notFound("故障单",id));f.setStatus("CLOSED");equipments.findByEquipmentCode(f.getEquipmentCode()).ifPresent(e->{e.setStatus("IDLE");equipments.save(e);});return ApiResponse.ok(faults.save(f));}
 @GetMapping("/inspections")public ApiResponse<Page<EquipmentInspection>> inspectionPage(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size){return ApiResponse.ok(inspections.findAll(PageRequest.of(Math.max(0,page-1),Math.min(size,200))));}
 @PostMapping("/inspections")public ApiResponse<EquipmentInspection> inspection(@RequestBody EquipmentInspection i){if(inspections.existsByInspectionNo(i.getInspectionNo()))throw BizException.of(ErrorCode.MASTER_DATA_ALREADY_EXISTS,"点检单号已存在");equipments.findByEquipmentCode(i.getEquipmentCode()).orElseThrow(()->BizException.of(ErrorCode.MASTER_DATA_NOT_FOUND,"设备不存在"));i.setResult(null);i.setMissed(false);return ApiResponse.ok(inspections.save(i));}
 @PostMapping("/inspections/{id}/complete")public ApiResponse<EquipmentInspection> completeInspection(@PathVariable Long id,@RequestParam String result,@RequestParam(required=false)String abnormalDesc){if(!java.util.Set.of("NORMAL","ABNORMAL").contains(result))throw BizException.of(ErrorCode.MASTER_DATA_INVALID_STATE,"点检结果只能是 NORMAL 或 ABNORMAL");EquipmentInspection i=inspections.findById(id).orElseThrow(()->BizException.notFound("点检单",id));i.setActualDate(java.time.LocalDate.now());i.setResult(result);i.setAbnormalDesc(abnormalDesc);i.setInspectorCode(CurrentUser.usernameOrSystem());return ApiResponse.ok(inspections.save(i));}}
